import {
  IconBookOpen,
  IconBuilding2,
  IconHotel,
  IconSettings,
  IconSliders,
  IconDollarSign,
  IconFileText,
  IconDownload,
  IconPalette,
  IconFolderOpen,
  IconUserCircle,
  IconBarChart3,
  IconBrain,
  IconPlus,
  IconFlaskConical,
  IconCalculator,
  IconBriefcase,
  IconPieChart,
  IconLandmark,
  IconBookOpenCheck,
} from "@/components/icons";
import { ManualSection } from "./types";

export const SECTIONS: ManualSection[] = [
  { id: "app-overview", title: "1. Application Overview", icon: BookOpen },
  { id: "mgmt-company", title: "2. Management Company", icon: Building2 },
  { id: "property-portfolio", title: "3. Property Portfolio (SPVs)", icon: Hotel },
  { id: "global-assumptions", title: "4. Global Assumptions", icon: Settings },
  { id: "property-assumptions", title: "5. Property-Level Assumptions", icon: Sliders },
  { id: "cashflow-streams", title: "6. Cash Flow Streams", icon: DollarSign },
  { id: "financial-statements", title: "7. Financial Statements", icon: FileText },
  { id: "export-system", title: "8. Export System", icon: Download },
  { id: "design-config", title: "9. Design Configuration", icon: Palette },
  { id: "scenario-mgmt", title: "10. Scenario Management", icon: FolderOpen },
  { id: "my-profile", title: "11. My Profile", icon: UserCircle },
  { id: "dashboard-kpis", title: "12. Dashboard & KPIs", icon: BarChart3 },
  { id: "ai-research", title: "13. AI Research & Calibration", icon: Brain },
  { id: "property-crud", title: "14. Property CRUD & Images", icon: Plus },
  { id: "testing-methodology", title: "15. Testing Methodology", icon: FlaskConical },
  { id: "property-formulas", title: "16. Property Financial Formulas", icon: Calculator },
  { id: "company-formulas", title: "17. Management Company Formulas", icon: Briefcase },
  { id: "consolidated-formulas", title: "18. Consolidated Portfolio Formulas", icon: PieChart },
  { id: "investment-returns", title: "19. Investment Returns (DCF/FCF/IRR)", icon: Landmark },
  { id: "funding-financing", title: "20. Funding, Financing & Refinancing", icon: DollarSign },
  { id: "glossary", title: "21. Glossary", icon: BookOpenCheck },
];
