export type { IconProps } from './icon-utils';

export * from './navigation-icons';
export * from './financial-icons';
export * from './status-icons';
export * from './media-icons';
export * from './action-icons';
export * from './data-display-icons';
export * from './misc-icons';

import { IconAudioLines, IconCamera, IconMic, IconPause, IconPhone, IconPhoneOff, IconPlay, IconSend } from './media-icons';
import { IconBarChart3, IconCreditCard, IconTrendingDown, IconTrendingUp } from './financial-icons';
import { IconBell, IconCheckCircle2, IconCheckCircle, IconHelpCircle, IconSettings } from './status-icons';
import { IconClipboardList, IconDatabase, IconFileCode, IconFile, IconFileText, IconFolder } from './data-display-icons';
import { IconColumns, IconLayoutDashboard, IconList, IconLogOut, IconMoreVertical } from './navigation-icons';
import { IconCopy, IconMail, IconPlus, IconPlusCircle, IconShare } from './action-icons';
import { IconSquare } from './misc-icons';
import { IconUserCircle, IconUsers } from './misc-icons';

export const IconAudioLinesIcon = IconAudioLines;
export const IconBarChartIcon = IconBarChart3;
export const IconBellIcon = IconBell;
export const IconCameraIcon = IconCamera;
export const IconCheckCircle2Icon = IconCheckCircle2;
export const IconCheckCircleIcon = IconCheckCircle;
export const IconClipboardListIcon = IconClipboardList;
export const IconColumnsIcon = IconColumns;
export const IconCopyIcon = IconCopy;
export const IconCreditCardIcon = IconCreditCard;
export const IconDatabaseIcon = IconDatabase;
export const IconFileCodeIcon = IconFileCode;
export const IconFileIcon = IconFile;
export const IconFileTextIcon = IconFileText;
export const IconFolderIcon = IconFolder;
export const IconHelpCircleIcon = IconHelpCircle;
export const IconLayoutDashboardIcon = IconLayoutDashboard;
export const IconListIcon = IconList;
export const IconLogOutIcon = IconLogOut;
export const IconMailIcon = IconMail;
export const IconMicIcon = IconMic;
export const IconMoreVerticalIcon = IconMoreVertical;
export const IconPauseIcon = IconPause;
export const IconPhoneIcon = IconPhone;
export const IconPhoneOffIcon = IconPhoneOff;
export const IconPlayIcon = IconPlay;
export const IconPlusCircleIcon = IconPlusCircle;
export const IconPlusIcon = IconPlus;
export const IconSendIcon = IconSend;
export const IconSettingsIcon = IconSettings;
export const IconShareIcon = IconShare;
export const IconSquareIcon = IconSquare;
export const IconTrendingDownIcon = IconTrendingDown;
export const IconTrendingUpIcon = IconTrendingUp;
export const IconUserCircleIcon = IconUserCircle;
export const IconUsersIcon = IconUsers;
