-- =============================================================================
-- FULL SYNC: Dev → Production (runs ALL scripts in order)
-- WARNING: This overwrites ALL production data including assumptions!
-- If you only want to sync structure/users without touching assumptions,
-- run scripts 01 and 02 individually instead.
-- =============================================================================
-- To run individual pieces, use the numbered scripts:
--   01-structure.sql        — Companies, Logos, User Groups, Themes (safe)
--   02-users.sql            — User accounts (safe, passwords reset on startup)
--   03-global-assumptions   — Systemwide settings (OVERWRITES production changes)
--   04-properties.sql       — All 6 properties (OVERWRITES production changes)
--   05-fee-categories.sql   — Service fee categories (run after 04)
--   06-sequences.sql        — Reset auto-increment counters (run last)
-- =============================================================================
