-- =============================================================================
-- SCRIPT 4: Properties (all 6 hotels with full assumptions)
-- WARNING: This OVERWRITES any property assumption changes you made in
-- production! Only run this if you want to reset properties to dev values.
-- Also removes any non-canonical properties (old test data).
-- =============================================================================

-- Remove any properties that aren't part of the canonical 6
DELETE FROM property_fee_categories WHERE property_id NOT IN (32, 33, 35, 39, 41, 43);
DELETE FROM market_research WHERE type = 'property' AND property_id NOT IN (32, 33, 35, 39, 41, 43);
DELETE FROM properties WHERE id NOT IN (32, 33, 35, 39, 41, 43);

-- 1. Jano Grande Ranch (Jun 2026) — Medellín, Colombia — Full Equity + Refi
INSERT INTO properties (
  id, name, location, market, image_url, status,
  acquisition_date, operations_start_date,
  purchase_price, building_improvements, pre_opening_costs, operating_reserve,
  room_count, start_adr, adr_growth_rate, start_occupancy, max_occupancy,
  occupancy_ramp_months, occupancy_growth_step, stabilization_months, type,
  acquisition_ltv, acquisition_interest_rate, acquisition_term_years, acquisition_closing_cost_rate,
  will_refinance, refinance_date, refinance_ltv, refinance_interest_rate, refinance_term_years, refinance_closing_cost_rate,
  cost_rate_rooms, cost_rate_fb, cost_rate_admin, cost_rate_marketing, cost_rate_property_ops,
  cost_rate_utilities, cost_rate_insurance, cost_rate_taxes, cost_rate_it, cost_rate_ffe, cost_rate_other,
  rev_share_events, rev_share_fb, rev_share_other,
  catering_boost_percent, exit_cap_rate, tax_rate, land_value_percent, disposition_commission,
  base_management_fee_rate, incentive_management_fee_rate,
  street_address, city, state_province, zip_postal_code, country,
  research_values, user_id, refinance_years_after_acquisition
) OVERRIDING SYSTEM VALUE VALUES (
  35, 'Jano Grande Ranch', 'Antioquia, Medellín', 'Latin America', '/images/property-medellin.png', 'Planned',
  '2026-06-01', '2026-12-01',
  1200000, 400000, 150000, 300000,
  20, 250, 0.035, 0.4, 0.72,
  9, 0.05, 36, 'Full Equity',
  0.6, 0.095, 25, 0.03,
  'Yes', '2029-12-01', 0.75, 0.09, 25, 0.03,
  0.17, 0.1, 0.06, 0.015, 0.05,
  0.04, 0.018, 0.016, 0.005, 0.04, 0.05,
  0.3, 0.25, 0.08,
  0.25, 0.1, 0.09, 0.35, 0.05,
  0.085, 0.12,
  'Vereda El Salado', 'Medellín', 'Antioquia', '050001', 'Colombia',
  '{"adr": {"mid": 180, "source": "seed", "display": "$120–$260"}, "costFB": {"mid": 9, "source": "seed", "display": "7%–12%"}, "costIT": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "capRate": {"mid": 10.5, "source": "seed", "display": "9%–12%"}, "costFFE": {"mid": 4, "source": "seed", "display": "3%–5%"}, "catering": {"mid": 30, "source": "seed", "display": "25%–35%"}, "svcFeeIT": {"mid": 0.5, "source": "seed", "display": "0.3%–0.8%"}, "costAdmin": {"mid": 4, "source": "seed", "display": "3%–6%"}, "costOther": {"mid": 5, "source": "seed", "display": "3%–6%"}, "incomeTax": {"mid": 35, "source": "seed", "display": "30%–38%"}, "landValue": {"mid": 15, "source": "seed", "display": "10%–20%"}, "occupancy": {"mid": 62, "source": "seed", "display": "55%–70%"}, "rampMonths": {"mid": 18, "source": "seed", "display": "12–24 mo"}, "incentiveFee": {"mid": 10, "source": "seed", "display": "8%–12%"}, "costInsurance": {"mid": 0.3, "source": "seed", "display": "0.2%–0.5%"}, "costMarketing": {"mid": 2, "source": "seed", "display": "1%–3%"}, "costUtilities": {"mid": 2.5, "source": "seed", "display": "2%–3.5%"}, "startOccupancy": {"mid": 40, "source": "seed", "display": "30%–45%"}, "costPropertyOps": {"mid": 3, "source": "seed", "display": "2%–4%"}, "svcFeeMarketing": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costHousekeeping": {"mid": 14, "source": "seed", "display": "10%–18%"}, "svcFeeAccounting": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costPropertyTaxes": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "svcFeeGeneralMgmt": {"mid": 1, "source": "seed", "display": "0.7%–1.2%"}, "svcFeeReservations": {"mid": 1.5, "source": "seed", "display": "1%–2%"}}',
  NULL, 3
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, location = EXCLUDED.location, market = EXCLUDED.market, image_url = EXCLUDED.image_url,
  status = EXCLUDED.status, acquisition_date = EXCLUDED.acquisition_date, operations_start_date = EXCLUDED.operations_start_date,
  purchase_price = EXCLUDED.purchase_price, building_improvements = EXCLUDED.building_improvements,
  pre_opening_costs = EXCLUDED.pre_opening_costs, operating_reserve = EXCLUDED.operating_reserve,
  room_count = EXCLUDED.room_count, start_adr = EXCLUDED.start_adr, adr_growth_rate = EXCLUDED.adr_growth_rate,
  start_occupancy = EXCLUDED.start_occupancy, max_occupancy = EXCLUDED.max_occupancy,
  occupancy_ramp_months = EXCLUDED.occupancy_ramp_months, occupancy_growth_step = EXCLUDED.occupancy_growth_step,
  stabilization_months = EXCLUDED.stabilization_months, type = EXCLUDED.type,
  acquisition_ltv = EXCLUDED.acquisition_ltv, acquisition_interest_rate = EXCLUDED.acquisition_interest_rate,
  acquisition_term_years = EXCLUDED.acquisition_term_years, acquisition_closing_cost_rate = EXCLUDED.acquisition_closing_cost_rate,
  will_refinance = EXCLUDED.will_refinance, refinance_date = EXCLUDED.refinance_date,
  refinance_ltv = EXCLUDED.refinance_ltv, refinance_interest_rate = EXCLUDED.refinance_interest_rate,
  refinance_term_years = EXCLUDED.refinance_term_years, refinance_closing_cost_rate = EXCLUDED.refinance_closing_cost_rate,
  cost_rate_rooms = EXCLUDED.cost_rate_rooms, cost_rate_fb = EXCLUDED.cost_rate_fb,
  cost_rate_admin = EXCLUDED.cost_rate_admin, cost_rate_marketing = EXCLUDED.cost_rate_marketing,
  cost_rate_property_ops = EXCLUDED.cost_rate_property_ops, cost_rate_utilities = EXCLUDED.cost_rate_utilities,
  cost_rate_insurance = EXCLUDED.cost_rate_insurance, cost_rate_taxes = EXCLUDED.cost_rate_taxes,
  cost_rate_it = EXCLUDED.cost_rate_it, cost_rate_ffe = EXCLUDED.cost_rate_ffe, cost_rate_other = EXCLUDED.cost_rate_other,
  rev_share_events = EXCLUDED.rev_share_events, rev_share_fb = EXCLUDED.rev_share_fb, rev_share_other = EXCLUDED.rev_share_other,
  catering_boost_percent = EXCLUDED.catering_boost_percent, exit_cap_rate = EXCLUDED.exit_cap_rate,
  tax_rate = EXCLUDED.tax_rate, land_value_percent = EXCLUDED.land_value_percent,
  disposition_commission = EXCLUDED.disposition_commission,
  base_management_fee_rate = EXCLUDED.base_management_fee_rate, incentive_management_fee_rate = EXCLUDED.incentive_management_fee_rate,
  street_address = EXCLUDED.street_address, city = EXCLUDED.city, state_province = EXCLUDED.state_province,
  zip_postal_code = EXCLUDED.zip_postal_code, country = EXCLUDED.country,
  research_values = EXCLUDED.research_values, refinance_years_after_acquisition = EXCLUDED.refinance_years_after_acquisition;

-- 2. Loch Sheldrake (Nov 2026) — Sullivan County, NY — Full Equity + Refi
INSERT INTO properties (
  id, name, location, market, image_url, status,
  acquisition_date, operations_start_date,
  purchase_price, building_improvements, pre_opening_costs, operating_reserve,
  room_count, start_adr, adr_growth_rate, start_occupancy, max_occupancy,
  occupancy_ramp_months, occupancy_growth_step, stabilization_months, type,
  acquisition_ltv, acquisition_interest_rate, acquisition_term_years, acquisition_closing_cost_rate,
  will_refinance, refinance_date, refinance_ltv, refinance_interest_rate, refinance_term_years, refinance_closing_cost_rate,
  cost_rate_rooms, cost_rate_fb, cost_rate_admin, cost_rate_marketing, cost_rate_property_ops,
  cost_rate_utilities, cost_rate_insurance, cost_rate_taxes, cost_rate_it, cost_rate_ffe, cost_rate_other,
  rev_share_events, rev_share_fb, rev_share_other,
  catering_boost_percent, exit_cap_rate, tax_rate, land_value_percent, disposition_commission,
  base_management_fee_rate, incentive_management_fee_rate,
  street_address, city, state_province, zip_postal_code, country,
  research_values, user_id, refinance_years_after_acquisition
) OVERRIDING SYSTEM VALUE VALUES (
  43, 'Loch Sheldrake', 'Sullivan County, New York', 'North America', '/images/property-loch-sheldrake.png', 'Planned',
  '2026-11-01', '2027-05-01',
  3000000, 1000000, 150000, 400000,
  20, 280, 0.035, 0.5, 0.68,
  4, 0.05, 18, 'Full Equity',
  0.65, 0.075, 25, 0.025,
  'Yes', '2030-05-01', 0.75, 0.09, 25, 0.03,
  0.19, 0.09, 0.07, 0.02, 0.055,
  0.055, 0.028, 0.035, 0.005, 0.04, 0.04,
  0.35, 0.25, 0.08,
  0.22, 0.09, 0.25, 0.3, 0.05,
  0.085, 0.12,
  'Loch Sheldrake', 'Loch Sheldrake', 'New York', '12759', 'United States',
  '{"adr": {"mid": 310, "source": "seed", "display": "$240–$380"}, "costFB": {"mid": 9, "source": "seed", "display": "7%–12%"}, "costIT": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "capRate": {"mid": 8.5, "source": "seed", "display": "7.5%–9.5%"}, "costFFE": {"mid": 4, "source": "seed", "display": "3%–5%"}, "catering": {"mid": 28, "source": "seed", "display": "22%–35%"}, "svcFeeIT": {"mid": 0.5, "source": "seed", "display": "0.3%–0.8%"}, "costAdmin": {"mid": 5.5, "source": "seed", "display": "4%–7%"}, "costOther": {"mid": 5, "source": "seed", "display": "3%–6%"}, "incomeTax": {"mid": 30, "source": "seed", "display": "28%–33%"}, "landValue": {"mid": 30, "source": "seed", "display": "25%–35%"}, "occupancy": {"mid": 68, "source": "seed", "display": "60%–75%"}, "rampMonths": {"mid": 15, "source": "seed", "display": "12–18 mo"}, "incentiveFee": {"mid": 10, "source": "seed", "display": "8%–12%"}, "costInsurance": {"mid": 0.5, "source": "seed", "display": "0.3%–0.7%"}, "costMarketing": {"mid": 2, "source": "seed", "display": "1%–3%"}, "costUtilities": {"mid": 4.5, "source": "seed", "display": "3.5%–5.5%"}, "startOccupancy": {"mid": 45, "source": "seed", "display": "35%–50%"}, "costPropertyOps": {"mid": 4, "source": "seed", "display": "3%–5%"}, "svcFeeMarketing": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costHousekeeping": {"mid": 18, "source": "seed", "display": "14%–22%"}, "svcFeeAccounting": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costPropertyTaxes": {"mid": 2.2, "source": "seed", "display": "1.8%–2.8%"}, "svcFeeGeneralMgmt": {"mid": 1, "source": "seed", "display": "0.7%–1.2%"}, "svcFeeReservations": {"mid": 1.5, "source": "seed", "display": "1%–2%"}}',
  1, 3
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, location = EXCLUDED.location, market = EXCLUDED.market, image_url = EXCLUDED.image_url,
  status = EXCLUDED.status, acquisition_date = EXCLUDED.acquisition_date, operations_start_date = EXCLUDED.operations_start_date,
  purchase_price = EXCLUDED.purchase_price, building_improvements = EXCLUDED.building_improvements,
  pre_opening_costs = EXCLUDED.pre_opening_costs, operating_reserve = EXCLUDED.operating_reserve,
  room_count = EXCLUDED.room_count, start_adr = EXCLUDED.start_adr, adr_growth_rate = EXCLUDED.adr_growth_rate,
  start_occupancy = EXCLUDED.start_occupancy, max_occupancy = EXCLUDED.max_occupancy,
  occupancy_ramp_months = EXCLUDED.occupancy_ramp_months, occupancy_growth_step = EXCLUDED.occupancy_growth_step,
  stabilization_months = EXCLUDED.stabilization_months, type = EXCLUDED.type,
  acquisition_ltv = EXCLUDED.acquisition_ltv, acquisition_interest_rate = EXCLUDED.acquisition_interest_rate,
  acquisition_term_years = EXCLUDED.acquisition_term_years, acquisition_closing_cost_rate = EXCLUDED.acquisition_closing_cost_rate,
  will_refinance = EXCLUDED.will_refinance, refinance_date = EXCLUDED.refinance_date,
  refinance_ltv = EXCLUDED.refinance_ltv, refinance_interest_rate = EXCLUDED.refinance_interest_rate,
  refinance_term_years = EXCLUDED.refinance_term_years, refinance_closing_cost_rate = EXCLUDED.refinance_closing_cost_rate,
  cost_rate_rooms = EXCLUDED.cost_rate_rooms, cost_rate_fb = EXCLUDED.cost_rate_fb,
  cost_rate_admin = EXCLUDED.cost_rate_admin, cost_rate_marketing = EXCLUDED.cost_rate_marketing,
  cost_rate_property_ops = EXCLUDED.cost_rate_property_ops, cost_rate_utilities = EXCLUDED.cost_rate_utilities,
  cost_rate_insurance = EXCLUDED.cost_rate_insurance, cost_rate_taxes = EXCLUDED.cost_rate_taxes,
  cost_rate_it = EXCLUDED.cost_rate_it, cost_rate_ffe = EXCLUDED.cost_rate_ffe, cost_rate_other = EXCLUDED.cost_rate_other,
  rev_share_events = EXCLUDED.rev_share_events, rev_share_fb = EXCLUDED.rev_share_fb, rev_share_other = EXCLUDED.rev_share_other,
  catering_boost_percent = EXCLUDED.catering_boost_percent, exit_cap_rate = EXCLUDED.exit_cap_rate,
  tax_rate = EXCLUDED.tax_rate, land_value_percent = EXCLUDED.land_value_percent,
  disposition_commission = EXCLUDED.disposition_commission,
  base_management_fee_rate = EXCLUDED.base_management_fee_rate, incentive_management_fee_rate = EXCLUDED.incentive_management_fee_rate,
  street_address = EXCLUDED.street_address, city = EXCLUDED.city, state_province = EXCLUDED.state_province,
  zip_postal_code = EXCLUDED.zip_postal_code, country = EXCLUDED.country,
  research_values = EXCLUDED.research_values, user_id = EXCLUDED.user_id,
  refinance_years_after_acquisition = EXCLUDED.refinance_years_after_acquisition;

-- 3. Belleayre Mountain (Mar 2027) — Western Catskills, NY — Full Equity + Refi
INSERT INTO properties (
  id, name, location, market, image_url, status,
  acquisition_date, operations_start_date,
  purchase_price, building_improvements, pre_opening_costs, operating_reserve,
  room_count, start_adr, adr_growth_rate, start_occupancy, max_occupancy,
  occupancy_ramp_months, occupancy_growth_step, stabilization_months, type,
  acquisition_ltv, acquisition_interest_rate, acquisition_term_years, acquisition_closing_cost_rate,
  will_refinance, refinance_date, refinance_ltv, refinance_interest_rate, refinance_term_years, refinance_closing_cost_rate,
  cost_rate_rooms, cost_rate_fb, cost_rate_admin, cost_rate_marketing, cost_rate_property_ops,
  cost_rate_utilities, cost_rate_insurance, cost_rate_taxes, cost_rate_it, cost_rate_ffe, cost_rate_other,
  rev_share_events, rev_share_fb, rev_share_other,
  catering_boost_percent, exit_cap_rate, tax_rate, land_value_percent, disposition_commission,
  base_management_fee_rate, incentive_management_fee_rate,
  street_address, city, state_province, zip_postal_code, country,
  research_values, user_id, refinance_years_after_acquisition
) OVERRIDING SYSTEM VALUE VALUES (
  32, 'Belleayre Mountain', 'Western Catskills, New York', 'North America', '/images/property-belleayre.png', 'Planned',
  '2027-03-01', '2027-09-01',
  3500000, 800000, 250000, 500000,
  20, 320, 0.035, 0.4, 0.68,
  12, 0.05, 36, 'Full Equity',
  0.65, 0.075, 25, 0.025,
  'Yes', '2030-09-01', 0.75, 0.09, 25, 0.03,
  0.2, 0.09, 0.08, 0.02, 0.06,
  0.055, 0.03, 0.035, 0.005, 0.04, 0.04,
  0.3, 0.28, 0.07,
  0.2, 0.085, 0.25, 0.4, 0.05,
  0.085, 0.12,
  'Upper Delaware River Valley', 'Highmount', 'New York', '12441', 'United States',
  '{"adr": {"mid": 350, "source": "seed", "display": "$280–$450"}, "costFB": {"mid": 9, "source": "seed", "display": "7%–12%"}, "costIT": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "capRate": {"mid": 7.5, "source": "seed", "display": "6.5%–8.5%"}, "costFFE": {"mid": 4, "source": "seed", "display": "3%–5%"}, "catering": {"mid": 30, "source": "seed", "display": "25%–35%"}, "svcFeeIT": {"mid": 0.5, "source": "seed", "display": "0.3%–0.8%"}, "costAdmin": {"mid": 5, "source": "seed", "display": "4%–7%"}, "costOther": {"mid": 5, "source": "seed", "display": "3%–6%"}, "incomeTax": {"mid": 31, "source": "seed", "display": "29%–34%"}, "landValue": {"mid": 40, "source": "seed", "display": "30%–50%"}, "occupancy": {"mid": 76, "source": "seed", "display": "70%–82%"}, "rampMonths": {"mid": 18, "source": "seed", "display": "12–24 mo"}, "incentiveFee": {"mid": 10, "source": "seed", "display": "8%–12%"}, "costInsurance": {"mid": 0.6, "source": "seed", "display": "0.4%–0.8%"}, "costMarketing": {"mid": 2, "source": "seed", "display": "1%–3%"}, "costUtilities": {"mid": 4.2, "source": "seed", "display": "3.5%–5%"}, "startOccupancy": {"mid": 40, "source": "seed", "display": "30%–45%"}, "costPropertyOps": {"mid": 4, "source": "seed", "display": "3%–5%"}, "svcFeeMarketing": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costHousekeeping": {"mid": 20, "source": "seed", "display": "15%–22%"}, "svcFeeAccounting": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costPropertyTaxes": {"mid": 2.5, "source": "seed", "display": "1.8%–3.5%"}, "svcFeeGeneralMgmt": {"mid": 1, "source": "seed", "display": "0.7%–1.2%"}, "svcFeeReservations": {"mid": 1.5, "source": "seed", "display": "1%–2%"}}',
  NULL, 3
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, location = EXCLUDED.location, market = EXCLUDED.market, image_url = EXCLUDED.image_url,
  status = EXCLUDED.status, acquisition_date = EXCLUDED.acquisition_date, operations_start_date = EXCLUDED.operations_start_date,
  purchase_price = EXCLUDED.purchase_price, building_improvements = EXCLUDED.building_improvements,
  pre_opening_costs = EXCLUDED.pre_opening_costs, operating_reserve = EXCLUDED.operating_reserve,
  room_count = EXCLUDED.room_count, start_adr = EXCLUDED.start_adr, adr_growth_rate = EXCLUDED.adr_growth_rate,
  start_occupancy = EXCLUDED.start_occupancy, max_occupancy = EXCLUDED.max_occupancy,
  occupancy_ramp_months = EXCLUDED.occupancy_ramp_months, occupancy_growth_step = EXCLUDED.occupancy_growth_step,
  stabilization_months = EXCLUDED.stabilization_months, type = EXCLUDED.type,
  acquisition_ltv = EXCLUDED.acquisition_ltv, acquisition_interest_rate = EXCLUDED.acquisition_interest_rate,
  acquisition_term_years = EXCLUDED.acquisition_term_years, acquisition_closing_cost_rate = EXCLUDED.acquisition_closing_cost_rate,
  will_refinance = EXCLUDED.will_refinance, refinance_date = EXCLUDED.refinance_date,
  refinance_ltv = EXCLUDED.refinance_ltv, refinance_interest_rate = EXCLUDED.refinance_interest_rate,
  refinance_term_years = EXCLUDED.refinance_term_years, refinance_closing_cost_rate = EXCLUDED.refinance_closing_cost_rate,
  cost_rate_rooms = EXCLUDED.cost_rate_rooms, cost_rate_fb = EXCLUDED.cost_rate_fb,
  cost_rate_admin = EXCLUDED.cost_rate_admin, cost_rate_marketing = EXCLUDED.cost_rate_marketing,
  cost_rate_property_ops = EXCLUDED.cost_rate_property_ops, cost_rate_utilities = EXCLUDED.cost_rate_utilities,
  cost_rate_insurance = EXCLUDED.cost_rate_insurance, cost_rate_taxes = EXCLUDED.cost_rate_taxes,
  cost_rate_it = EXCLUDED.cost_rate_it, cost_rate_ffe = EXCLUDED.cost_rate_ffe, cost_rate_other = EXCLUDED.cost_rate_other,
  rev_share_events = EXCLUDED.rev_share_events, rev_share_fb = EXCLUDED.rev_share_fb, rev_share_other = EXCLUDED.rev_share_other,
  catering_boost_percent = EXCLUDED.catering_boost_percent, exit_cap_rate = EXCLUDED.exit_cap_rate,
  tax_rate = EXCLUDED.tax_rate, land_value_percent = EXCLUDED.land_value_percent,
  disposition_commission = EXCLUDED.disposition_commission,
  base_management_fee_rate = EXCLUDED.base_management_fee_rate, incentive_management_fee_rate = EXCLUDED.incentive_management_fee_rate,
  street_address = EXCLUDED.street_address, city = EXCLUDED.city, state_province = EXCLUDED.state_province,
  zip_postal_code = EXCLUDED.zip_postal_code, country = EXCLUDED.country,
  research_values = EXCLUDED.research_values, refinance_years_after_acquisition = EXCLUDED.refinance_years_after_acquisition;

-- 4. Scott's House (Aug 2027) — Ogden Valley, Utah — Financed (no refi)
INSERT INTO properties (
  id, name, location, market, image_url, status,
  acquisition_date, operations_start_date,
  purchase_price, building_improvements, pre_opening_costs, operating_reserve,
  room_count, start_adr, adr_growth_rate, start_occupancy, max_occupancy,
  occupancy_ramp_months, occupancy_growth_step, stabilization_months, type,
  acquisition_ltv, acquisition_interest_rate, acquisition_term_years, acquisition_closing_cost_rate,
  will_refinance, refinance_date, refinance_ltv, refinance_interest_rate, refinance_term_years, refinance_closing_cost_rate,
  cost_rate_rooms, cost_rate_fb, cost_rate_admin, cost_rate_marketing, cost_rate_property_ops,
  cost_rate_utilities, cost_rate_insurance, cost_rate_taxes, cost_rate_it, cost_rate_ffe, cost_rate_other,
  rev_share_events, rev_share_fb, rev_share_other,
  catering_boost_percent, exit_cap_rate, tax_rate, land_value_percent, disposition_commission,
  base_management_fee_rate, incentive_management_fee_rate,
  street_address, city, state_province, zip_postal_code, country,
  research_values, user_id, refinance_years_after_acquisition
) OVERRIDING SYSTEM VALUE VALUES (
  39, 'Scott''s House', 'Ogden Valley, Utah', 'North America', '/images/property-eden.png', 'Planned',
  '2027-08-01', '2028-02-01',
  3200000, 800000, 200000, 400000,
  20, 350, 0.03, 0.45, 0.65,
  6, 0.05, 24, 'Financed',
  0.6, 0.07, 25, 0.025,
  NULL, NULL, NULL, NULL, NULL, NULL,
  0.2, 0.08, 0.07, 0.02, 0.05,
  0.05, 0.025, 0.02, 0.005, 0.04, 0.04,
  0.3, 0.2, 0.08,
  0.2, 0.085, 0.22, 0.3, 0.05,
  0.085, 0.12,
  'Eden', 'Eden', 'Utah', '84310', 'United States',
  '{"adr": {"mid": 380, "source": "seed", "display": "$300–$475"}, "costFB": {"mid": 8, "source": "seed", "display": "6%–10%"}, "costIT": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "capRate": {"mid": 8, "source": "seed", "display": "7%–9%"}, "costFFE": {"mid": 4, "source": "seed", "display": "3%–5%"}, "catering": {"mid": 32, "source": "seed", "display": "25%–40%"}, "svcFeeIT": {"mid": 0.5, "source": "seed", "display": "0.3%–0.8%"}, "costAdmin": {"mid": 5, "source": "seed", "display": "4%–7%"}, "costOther": {"mid": 5, "source": "seed", "display": "3%–6%"}, "incomeTax": {"mid": 25, "source": "seed", "display": "24%–26%"}, "landValue": {"mid": 30, "source": "seed", "display": "25%–35%"}, "occupancy": {"mid": 65, "source": "seed", "display": "58%–72%"}, "rampMonths": {"mid": 14, "source": "seed", "display": "10–18 mo"}, "incentiveFee": {"mid": 10, "source": "seed", "display": "8%–12%"}, "costInsurance": {"mid": 0.4, "source": "seed", "display": "0.3%–0.6%"}, "costMarketing": {"mid": 2, "source": "seed", "display": "1%–3%"}, "costUtilities": {"mid": 4.5, "source": "seed", "display": "3.5%–5.5%"}, "startOccupancy": {"mid": 42, "source": "seed", "display": "35%–50%"}, "costPropertyOps": {"mid": 4, "source": "seed", "display": "3%–5%"}, "svcFeeMarketing": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costHousekeeping": {"mid": 19, "source": "seed", "display": "15%–22%"}, "svcFeeAccounting": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costPropertyTaxes": {"mid": 0.9, "source": "seed", "display": "0.7%–1.2%"}, "svcFeeGeneralMgmt": {"mid": 1, "source": "seed", "display": "0.7%–1.2%"}, "svcFeeReservations": {"mid": 1.5, "source": "seed", "display": "1%–2%"}}',
  NULL, NULL
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, location = EXCLUDED.location, market = EXCLUDED.market, image_url = EXCLUDED.image_url,
  status = EXCLUDED.status, acquisition_date = EXCLUDED.acquisition_date, operations_start_date = EXCLUDED.operations_start_date,
  purchase_price = EXCLUDED.purchase_price, building_improvements = EXCLUDED.building_improvements,
  pre_opening_costs = EXCLUDED.pre_opening_costs, operating_reserve = EXCLUDED.operating_reserve,
  room_count = EXCLUDED.room_count, start_adr = EXCLUDED.start_adr, adr_growth_rate = EXCLUDED.adr_growth_rate,
  start_occupancy = EXCLUDED.start_occupancy, max_occupancy = EXCLUDED.max_occupancy,
  occupancy_ramp_months = EXCLUDED.occupancy_ramp_months, occupancy_growth_step = EXCLUDED.occupancy_growth_step,
  stabilization_months = EXCLUDED.stabilization_months, type = EXCLUDED.type,
  acquisition_ltv = EXCLUDED.acquisition_ltv, acquisition_interest_rate = EXCLUDED.acquisition_interest_rate,
  acquisition_term_years = EXCLUDED.acquisition_term_years, acquisition_closing_cost_rate = EXCLUDED.acquisition_closing_cost_rate,
  will_refinance = EXCLUDED.will_refinance, refinance_date = EXCLUDED.refinance_date,
  refinance_ltv = EXCLUDED.refinance_ltv, refinance_interest_rate = EXCLUDED.refinance_interest_rate,
  refinance_term_years = EXCLUDED.refinance_term_years, refinance_closing_cost_rate = EXCLUDED.refinance_closing_cost_rate,
  cost_rate_rooms = EXCLUDED.cost_rate_rooms, cost_rate_fb = EXCLUDED.cost_rate_fb,
  cost_rate_admin = EXCLUDED.cost_rate_admin, cost_rate_marketing = EXCLUDED.cost_rate_marketing,
  cost_rate_property_ops = EXCLUDED.cost_rate_property_ops, cost_rate_utilities = EXCLUDED.cost_rate_utilities,
  cost_rate_insurance = EXCLUDED.cost_rate_insurance, cost_rate_taxes = EXCLUDED.cost_rate_taxes,
  cost_rate_it = EXCLUDED.cost_rate_it, cost_rate_ffe = EXCLUDED.cost_rate_ffe, cost_rate_other = EXCLUDED.cost_rate_other,
  rev_share_events = EXCLUDED.rev_share_events, rev_share_fb = EXCLUDED.rev_share_fb, rev_share_other = EXCLUDED.rev_share_other,
  catering_boost_percent = EXCLUDED.catering_boost_percent, exit_cap_rate = EXCLUDED.exit_cap_rate,
  tax_rate = EXCLUDED.tax_rate, land_value_percent = EXCLUDED.land_value_percent,
  disposition_commission = EXCLUDED.disposition_commission,
  base_management_fee_rate = EXCLUDED.base_management_fee_rate, incentive_management_fee_rate = EXCLUDED.incentive_management_fee_rate,
  street_address = EXCLUDED.street_address, city = EXCLUDED.city, state_province = EXCLUDED.state_province,
  zip_postal_code = EXCLUDED.zip_postal_code, country = EXCLUDED.country,
  research_values = EXCLUDED.research_values;

-- 5. Lakeview Haven Lodge (Dec 2027) — Ogden Valley, Utah — Financed (no refi)
INSERT INTO properties (
  id, name, location, market, image_url, status,
  acquisition_date, operations_start_date,
  purchase_price, building_improvements, pre_opening_costs, operating_reserve,
  room_count, start_adr, adr_growth_rate, start_occupancy, max_occupancy,
  occupancy_ramp_months, occupancy_growth_step, stabilization_months, type,
  acquisition_ltv, acquisition_interest_rate, acquisition_term_years, acquisition_closing_cost_rate,
  will_refinance, refinance_date, refinance_ltv, refinance_interest_rate, refinance_term_years, refinance_closing_cost_rate,
  cost_rate_rooms, cost_rate_fb, cost_rate_admin, cost_rate_marketing, cost_rate_property_ops,
  cost_rate_utilities, cost_rate_insurance, cost_rate_taxes, cost_rate_it, cost_rate_ffe, cost_rate_other,
  rev_share_events, rev_share_fb, rev_share_other,
  catering_boost_percent, exit_cap_rate, tax_rate, land_value_percent, disposition_commission,
  base_management_fee_rate, incentive_management_fee_rate,
  street_address, city, state_province, zip_postal_code, country,
  research_values, user_id, refinance_years_after_acquisition
) OVERRIDING SYSTEM VALUE VALUES (
  33, 'Lakeview Haven Lodge', 'Ogden Valley, Utah', 'North America', '/images/property-huntsville.png', 'Planned',
  '2027-12-01', '2028-06-01',
  3800000, 1200000, 250000, 500000,
  20, 320, 0.03, 0.5, 0.68,
  3, 0.05, 18, 'Financed',
  0.65, 0.07, 25, 0.025,
  NULL, NULL, 0.75, 0.09, 25, 0.03,
  0.2, 0.09, 0.07, 0.02, 0.055,
  0.05, 0.025, 0.02, 0.005, 0.04, 0.04,
  0.28, 0.22, 0.1,
  0.18, 0.08, 0.22, 0.35, 0.05,
  0.085, 0.12,
  'Pineview Reservoir', 'Huntsville', 'Utah', '84317', 'United States',
  '{"adr": {"mid": 370, "source": "seed", "display": "$280–$475"}, "costFB": {"mid": 9, "source": "seed", "display": "7%–12%"}, "costIT": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "capRate": {"mid": 8.5, "source": "seed", "display": "8%–9.5%"}, "costFFE": {"mid": 4, "source": "seed", "display": "3%–5%"}, "catering": {"mid": 36, "source": "seed", "display": "30%–42%"}, "svcFeeIT": {"mid": 0.5, "source": "seed", "display": "0.3%–0.8%"}, "costAdmin": {"mid": 5, "source": "seed", "display": "4%–7%"}, "costOther": {"mid": 5, "source": "seed", "display": "3%–6%"}, "incomeTax": {"mid": 25, "source": "seed", "display": "24%–26%"}, "landValue": {"mid": 20, "source": "seed", "display": "15%–25%"}, "occupancy": {"mid": 62, "source": "seed", "display": "55%–70%"}, "rampMonths": {"mid": 18, "source": "seed", "display": "12–24 mo"}, "incentiveFee": {"mid": 10, "source": "seed", "display": "8%–12%"}, "costInsurance": {"mid": 0.4, "source": "seed", "display": "0.3%–0.5%"}, "costMarketing": {"mid": 2, "source": "seed", "display": "1%–3%"}, "costUtilities": {"mid": 4.2, "source": "seed", "display": "3.5%–5%"}, "startOccupancy": {"mid": 40, "source": "seed", "display": "30%–45%"}, "costPropertyOps": {"mid": 4, "source": "seed", "display": "3%–5%"}, "svcFeeMarketing": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costHousekeeping": {"mid": 20, "source": "seed", "display": "15%–22%"}, "svcFeeAccounting": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costPropertyTaxes": {"mid": 0.8, "source": "seed", "display": "0.6%–1.2%"}, "svcFeeGeneralMgmt": {"mid": 1, "source": "seed", "display": "0.7%–1.2%"}, "svcFeeReservations": {"mid": 1.5, "source": "seed", "display": "1%–2%"}}',
  NULL, NULL
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, location = EXCLUDED.location, market = EXCLUDED.market, image_url = EXCLUDED.image_url,
  status = EXCLUDED.status, acquisition_date = EXCLUDED.acquisition_date, operations_start_date = EXCLUDED.operations_start_date,
  purchase_price = EXCLUDED.purchase_price, building_improvements = EXCLUDED.building_improvements,
  pre_opening_costs = EXCLUDED.pre_opening_costs, operating_reserve = EXCLUDED.operating_reserve,
  room_count = EXCLUDED.room_count, start_adr = EXCLUDED.start_adr, adr_growth_rate = EXCLUDED.adr_growth_rate,
  start_occupancy = EXCLUDED.start_occupancy, max_occupancy = EXCLUDED.max_occupancy,
  occupancy_ramp_months = EXCLUDED.occupancy_ramp_months, occupancy_growth_step = EXCLUDED.occupancy_growth_step,
  stabilization_months = EXCLUDED.stabilization_months, type = EXCLUDED.type,
  acquisition_ltv = EXCLUDED.acquisition_ltv, acquisition_interest_rate = EXCLUDED.acquisition_interest_rate,
  acquisition_term_years = EXCLUDED.acquisition_term_years, acquisition_closing_cost_rate = EXCLUDED.acquisition_closing_cost_rate,
  will_refinance = EXCLUDED.will_refinance, refinance_date = EXCLUDED.refinance_date,
  refinance_ltv = EXCLUDED.refinance_ltv, refinance_interest_rate = EXCLUDED.refinance_interest_rate,
  refinance_term_years = EXCLUDED.refinance_term_years, refinance_closing_cost_rate = EXCLUDED.refinance_closing_cost_rate,
  cost_rate_rooms = EXCLUDED.cost_rate_rooms, cost_rate_fb = EXCLUDED.cost_rate_fb,
  cost_rate_admin = EXCLUDED.cost_rate_admin, cost_rate_marketing = EXCLUDED.cost_rate_marketing,
  cost_rate_property_ops = EXCLUDED.cost_rate_property_ops, cost_rate_utilities = EXCLUDED.cost_rate_utilities,
  cost_rate_insurance = EXCLUDED.cost_rate_insurance, cost_rate_taxes = EXCLUDED.cost_rate_taxes,
  cost_rate_it = EXCLUDED.cost_rate_it, cost_rate_ffe = EXCLUDED.cost_rate_ffe, cost_rate_other = EXCLUDED.cost_rate_other,
  rev_share_events = EXCLUDED.rev_share_events, rev_share_fb = EXCLUDED.rev_share_fb, rev_share_other = EXCLUDED.rev_share_other,
  catering_boost_percent = EXCLUDED.catering_boost_percent, exit_cap_rate = EXCLUDED.exit_cap_rate,
  tax_rate = EXCLUDED.tax_rate, land_value_percent = EXCLUDED.land_value_percent,
  disposition_commission = EXCLUDED.disposition_commission,
  base_management_fee_rate = EXCLUDED.base_management_fee_rate, incentive_management_fee_rate = EXCLUDED.incentive_management_fee_rate,
  street_address = EXCLUDED.street_address, city = EXCLUDED.city, state_province = EXCLUDED.state_province,
  zip_postal_code = EXCLUDED.zip_postal_code, country = EXCLUDED.country,
  research_values = EXCLUDED.research_values;

-- 6. San Diego (Apr 2028) — Cartagena, Colombia — Financed (no refi)
INSERT INTO properties (
  id, name, location, market, image_url, status,
  acquisition_date, operations_start_date,
  purchase_price, building_improvements, pre_opening_costs, operating_reserve,
  room_count, start_adr, adr_growth_rate, start_occupancy, max_occupancy,
  occupancy_ramp_months, occupancy_growth_step, stabilization_months, type,
  acquisition_ltv, acquisition_interest_rate, acquisition_term_years, acquisition_closing_cost_rate,
  will_refinance, refinance_date, refinance_ltv, refinance_interest_rate, refinance_term_years, refinance_closing_cost_rate,
  cost_rate_rooms, cost_rate_fb, cost_rate_admin, cost_rate_marketing, cost_rate_property_ops,
  cost_rate_utilities, cost_rate_insurance, cost_rate_taxes, cost_rate_it, cost_rate_ffe, cost_rate_other,
  rev_share_events, rev_share_fb, rev_share_other,
  catering_boost_percent, exit_cap_rate, tax_rate, land_value_percent, disposition_commission,
  base_management_fee_rate, incentive_management_fee_rate,
  street_address, city, state_province, zip_postal_code, country,
  research_values, user_id, refinance_years_after_acquisition
) OVERRIDING SYSTEM VALUE VALUES (
  41, 'San Diego', 'Cartagena, Colombia', 'Latin America', '/images/property-cartagena.png', 'Planned',
  '2028-04-01', '2028-10-01',
  2000000, 1000000, 250000, 500000,
  20, 240, 0.035, 0.42, 0.72,
  10, 0.05, 36, 'Financed',
  0.6, 0.095, 25, 0.02,
  NULL, NULL, NULL, NULL, NULL, NULL,
  0.17, 0.09, 0.07, 0.015, 0.035,
  0.04, 0.025, 0.025, 0.005, 0.04, 0.04,
  0.3, 0.24, 0.06,
  0.2, 0.09, 0.35, 0.3, 0.05,
  0.085, 0.12,
  'Cochera del Hobo, Barrio San Diego', 'Cartagena', 'Bolívar', '130001', 'Colombia',
  '{"adr": {"mid": 220, "source": "seed", "display": "$160–$280"}, "costFB": {"mid": 9, "source": "seed", "display": "7%–12%"}, "costIT": {"mid": 0.8, "source": "seed", "display": "0.5%–1.2%"}, "capRate": {"mid": 9.5, "source": "seed", "display": "8.5%–11%"}, "costFFE": {"mid": 4, "source": "seed", "display": "3%–5%"}, "catering": {"mid": 28, "source": "seed", "display": "22%–35%"}, "svcFeeIT": {"mid": 0.5, "source": "seed", "display": "0.3%–0.8%"}, "costAdmin": {"mid": 5, "source": "seed", "display": "3%–6%"}, "costOther": {"mid": 4, "source": "seed", "display": "3%–5%"}, "incomeTax": {"mid": 35, "source": "seed", "display": "33%–38%"}, "landValue": {"mid": 30, "source": "seed", "display": "25%–35%"}, "occupancy": {"mid": 70, "source": "seed", "display": "62%–78%"}, "rampMonths": {"mid": 18, "source": "seed", "display": "14–24 mo"}, "incentiveFee": {"mid": 10, "source": "seed", "display": "8%–12%"}, "costInsurance": {"mid": 0.4, "source": "seed", "display": "0.3%–0.6%"}, "costMarketing": {"mid": 2, "source": "seed", "display": "1%–3%"}, "costUtilities": {"mid": 3, "source": "seed", "display": "2%–4%"}, "startOccupancy": {"mid": 38, "source": "seed", "display": "30%–45%"}, "costPropertyOps": {"mid": 3.5, "source": "seed", "display": "2.5%–4.5%"}, "svcFeeMarketing": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costHousekeeping": {"mid": 15, "source": "seed", "display": "11%–18%"}, "svcFeeAccounting": {"mid": 1, "source": "seed", "display": "0.5%–1.5%"}, "costPropertyTaxes": {"mid": 1.5, "source": "seed", "display": "1%–2%"}, "svcFeeGeneralMgmt": {"mid": 1, "source": "seed", "display": "0.7%–1.2%"}, "svcFeeReservations": {"mid": 1.5, "source": "seed", "display": "1%–2%"}}',
  NULL, NULL
)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name, location = EXCLUDED.location, market = EXCLUDED.market, image_url = EXCLUDED.image_url,
  status = EXCLUDED.status, acquisition_date = EXCLUDED.acquisition_date, operations_start_date = EXCLUDED.operations_start_date,
  purchase_price = EXCLUDED.purchase_price, building_improvements = EXCLUDED.building_improvements,
  pre_opening_costs = EXCLUDED.pre_opening_costs, operating_reserve = EXCLUDED.operating_reserve,
  room_count = EXCLUDED.room_count, start_adr = EXCLUDED.start_adr, adr_growth_rate = EXCLUDED.adr_growth_rate,
  start_occupancy = EXCLUDED.start_occupancy, max_occupancy = EXCLUDED.max_occupancy,
  occupancy_ramp_months = EXCLUDED.occupancy_ramp_months, occupancy_growth_step = EXCLUDED.occupancy_growth_step,
  stabilization_months = EXCLUDED.stabilization_months, type = EXCLUDED.type,
  acquisition_ltv = EXCLUDED.acquisition_ltv, acquisition_interest_rate = EXCLUDED.acquisition_interest_rate,
  acquisition_term_years = EXCLUDED.acquisition_term_years, acquisition_closing_cost_rate = EXCLUDED.acquisition_closing_cost_rate,
  will_refinance = EXCLUDED.will_refinance, refinance_date = EXCLUDED.refinance_date,
  refinance_ltv = EXCLUDED.refinance_ltv, refinance_interest_rate = EXCLUDED.refinance_interest_rate,
  refinance_term_years = EXCLUDED.refinance_term_years, refinance_closing_cost_rate = EXCLUDED.refinance_closing_cost_rate,
  cost_rate_rooms = EXCLUDED.cost_rate_rooms, cost_rate_fb = EXCLUDED.cost_rate_fb,
  cost_rate_admin = EXCLUDED.cost_rate_admin, cost_rate_marketing = EXCLUDED.cost_rate_marketing,
  cost_rate_property_ops = EXCLUDED.cost_rate_property_ops, cost_rate_utilities = EXCLUDED.cost_rate_utilities,
  cost_rate_insurance = EXCLUDED.cost_rate_insurance, cost_rate_taxes = EXCLUDED.cost_rate_taxes,
  cost_rate_it = EXCLUDED.cost_rate_it, cost_rate_ffe = EXCLUDED.cost_rate_ffe, cost_rate_other = EXCLUDED.cost_rate_other,
  rev_share_events = EXCLUDED.rev_share_events, rev_share_fb = EXCLUDED.rev_share_fb, rev_share_other = EXCLUDED.rev_share_other,
  catering_boost_percent = EXCLUDED.catering_boost_percent, exit_cap_rate = EXCLUDED.exit_cap_rate,
  tax_rate = EXCLUDED.tax_rate, land_value_percent = EXCLUDED.land_value_percent,
  disposition_commission = EXCLUDED.disposition_commission,
  base_management_fee_rate = EXCLUDED.base_management_fee_rate, incentive_management_fee_rate = EXCLUDED.incentive_management_fee_rate,
  street_address = EXCLUDED.street_address, city = EXCLUDED.city, state_province = EXCLUDED.state_province,
  zip_postal_code = EXCLUDED.zip_postal_code, country = EXCLUDED.country,
  research_values = EXCLUDED.research_values;
