-- Step 2: Global Assumptions
-- Run this SECOND in the production database

INSERT INTO global_assumptions (id, model_start_date, inflation_rate, base_management_fee, incentive_management_fee, staff_salary, travel_cost_per_client, it_license_per_client, marketing_rate, misc_ops_rate, office_lease_start, professional_services_start, tech_infra_start, business_insurance_start, standard_acq_package, debt_assumptions, updated_at, commission_rate, full_catering_fb_boost, partial_catering_fb_boost, fixed_cost_escalation_rate, safe_tranche1_amount, safe_tranche1_date, safe_tranche2_amount, safe_tranche2_date, safe_valuation_cap, safe_discount_rate, company_tax_rate, company_ops_start_date, fiscal_year_start_month, partner_comp_year1, partner_comp_year2, partner_comp_year3, partner_comp_year4, partner_comp_year5, partner_comp_year6, partner_comp_year7, partner_comp_year8, partner_comp_year9, partner_comp_year10, partner_count_year1, partner_count_year2, partner_count_year3, partner_count_year4, partner_count_year5, partner_count_year6, partner_count_year7, partner_count_year8, partner_count_year9, partner_count_year10, user_id, company_name, company_logo, funding_source_label, exit_cap_rate, sales_commission_rate, event_expense_rate, other_expense_rate, utilities_variable_split) VALUES
(2, '2026-04-01', 0.03, 0.05, 0.15, 75000, 12000, 3000, 0.05, 0.03, 36000, 24000, 18000, 12000, 
 '{"monthsToOps": 6, "purchasePrice": 2300000, "preOpeningCosts": 150000, "operatingReserve": 200000, "buildingImprovements": 800000}',
 '{"acqLTV": 0.75, "refiLTV": 0.75, "interestRate": 0.09, "amortizationYears": 25, "acqClosingCostRate": 0.02, "refiClosingCostRate": 0.03}',
 '2026-01-31 20:37:19.645', 0.06, 0.5, 0.25, 0.03, 750000, '2026-06-01', 750000, '2027-04-01', 2500000, 0.2, 0.3, '2026-06-01', 1, 540000, 540000, 540000, 600000, 600000, 700000, 700000, 800000, 800000, 900000, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, NULL, 'L+B Hospitality Company', NULL, 'SAFE', 0.085, 0.05, 0.65, 0.6, 0.6)
ON CONFLICT (id) DO UPDATE SET
  model_start_date = EXCLUDED.model_start_date,
  inflation_rate = EXCLUDED.inflation_rate,
  base_management_fee = EXCLUDED.base_management_fee,
  incentive_management_fee = EXCLUDED.incentive_management_fee,
  staff_salary = EXCLUDED.staff_salary,
  travel_cost_per_client = EXCLUDED.travel_cost_per_client,
  it_license_per_client = EXCLUDED.it_license_per_client,
  marketing_rate = EXCLUDED.marketing_rate,
  misc_ops_rate = EXCLUDED.misc_ops_rate,
  office_lease_start = EXCLUDED.office_lease_start,
  professional_services_start = EXCLUDED.professional_services_start,
  tech_infra_start = EXCLUDED.tech_infra_start,
  business_insurance_start = EXCLUDED.business_insurance_start,
  standard_acq_package = EXCLUDED.standard_acq_package,
  debt_assumptions = EXCLUDED.debt_assumptions,
  updated_at = EXCLUDED.updated_at,
  commission_rate = EXCLUDED.commission_rate,
  full_catering_fb_boost = EXCLUDED.full_catering_fb_boost,
  partial_catering_fb_boost = EXCLUDED.partial_catering_fb_boost,
  fixed_cost_escalation_rate = EXCLUDED.fixed_cost_escalation_rate,
  safe_tranche1_amount = EXCLUDED.safe_tranche1_amount,
  safe_tranche1_date = EXCLUDED.safe_tranche1_date,
  safe_tranche2_amount = EXCLUDED.safe_tranche2_amount,
  safe_tranche2_date = EXCLUDED.safe_tranche2_date,
  safe_valuation_cap = EXCLUDED.safe_valuation_cap,
  safe_discount_rate = EXCLUDED.safe_discount_rate,
  company_tax_rate = EXCLUDED.company_tax_rate,
  company_ops_start_date = EXCLUDED.company_ops_start_date,
  fiscal_year_start_month = EXCLUDED.fiscal_year_start_month,
  partner_comp_year1 = EXCLUDED.partner_comp_year1,
  partner_comp_year2 = EXCLUDED.partner_comp_year2,
  partner_comp_year3 = EXCLUDED.partner_comp_year3,
  partner_comp_year4 = EXCLUDED.partner_comp_year4,
  partner_comp_year5 = EXCLUDED.partner_comp_year5,
  partner_comp_year6 = EXCLUDED.partner_comp_year6,
  partner_comp_year7 = EXCLUDED.partner_comp_year7,
  partner_comp_year8 = EXCLUDED.partner_comp_year8,
  partner_comp_year9 = EXCLUDED.partner_comp_year9,
  partner_comp_year10 = EXCLUDED.partner_comp_year10,
  partner_count_year1 = EXCLUDED.partner_count_year1,
  partner_count_year2 = EXCLUDED.partner_count_year2,
  partner_count_year3 = EXCLUDED.partner_count_year3,
  partner_count_year4 = EXCLUDED.partner_count_year4,
  partner_count_year5 = EXCLUDED.partner_count_year5,
  partner_count_year6 = EXCLUDED.partner_count_year6,
  partner_count_year7 = EXCLUDED.partner_count_year7,
  partner_count_year8 = EXCLUDED.partner_count_year8,
  partner_count_year9 = EXCLUDED.partner_count_year9,
  partner_count_year10 = EXCLUDED.partner_count_year10,
  company_name = EXCLUDED.company_name,
  funding_source_label = EXCLUDED.funding_source_label,
  exit_cap_rate = EXCLUDED.exit_cap_rate,
  sales_commission_rate = EXCLUDED.sales_commission_rate,
  event_expense_rate = EXCLUDED.event_expense_rate,
  other_expense_rate = EXCLUDED.other_expense_rate,
  utilities_variable_split = EXCLUDED.utilities_variable_split;

SELECT setval('global_assumptions_id_seq', (SELECT MAX(id) FROM global_assumptions));
