import { sql } from "drizzle-orm";
import { pgTable, text, varchar, real, integer, timestamp, jsonb, boolean, index, serial, unique, check, primaryKey } from "drizzle-orm/pg-core";
import { createInsertSchema, createSelectSchema } from "drizzle-zod";
import { z } from "zod";

// --- COMPANIES TABLE ---
// Represents legal entities in the system. There are two types:
//   - "management": The hospitality management company that operates hotels
//   - "spv": Special Purpose Vehicle — a separate LLC created for each property
//     to isolate liability (standard practice in real estate private equity)
export const companies = pgTable("companies", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  name: text("name").notNull().unique(),
  type: text("type").notNull().default("spv"),
  description: text("description"),
  logoId: integer("logo_id").references(() => logos.id, { onDelete: "set null" }),
  themeId: integer("theme_id").references(() => designThemes.id, { onDelete: "set null" }),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertCompanySchema = z.object({
  name: z.string().min(1),
  type: z.enum(["management", "spv"]).optional().default("spv"),
  description: z.string().nullable().optional(),
  logoId: z.number().nullable().optional(),
  themeId: z.number().nullable().optional(),
  isActive: z.boolean().optional(),
});

export type Company = typeof companies.$inferSelect;
export type InsertCompany = z.infer<typeof insertCompanySchema>;


// --- LOGOS TABLE ---
// Stores company/brand logos for white-label presentation. Each logo has a
// companyName field so that the displayed brand name changes along with the logo.
// One logo is marked isDefault and used as the fallback when no group-specific logo exists.
export const logos = pgTable("logos", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  name: text("name").notNull(),
  companyName: text("company_name").notNull().default("Hospitality Business Group"),
  url: text("url").notNull(),
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertLogoSchema = z.object({
  name: z.string(),
  companyName: z.string(),
  url: z.string(),
  isDefault: z.boolean().optional(),
});

export type Logo = typeof logos.$inferSelect;
export type InsertLogo = z.infer<typeof insertLogoSchema>;


// --- RESEARCH VALUE TYPES ---
// When AI research is generated for a property, the LLM produces numeric estimates
// (e.g. market ADR, RevPAR, cap rates) along with display labels. Each value tracks
// its source: "ai" (generated by LLM), "seed" (pre-populated defaults),
// "market" (live API data from FRED/BLS/etc.), or "none".
export const researchValueSourceEnum = z.enum(["ai", "seed", "market", "none"]);
export type ResearchValueSource = z.infer<typeof researchValueSourceEnum>;

export const researchValueEntrySchema = z.object({
  display: z.string(),
  mid: z.number(),
  source: researchValueSourceEnum,
  sourceName: z.string().optional(),   // e.g. "FRED SOFR", "HVS 2025", "AI Jan 2026"
  sourceDate: z.string().optional(),   // ISO date of when the data was published/fetched
});
export type ResearchValueEntry = z.infer<typeof researchValueEntrySchema>;

export const researchValueMapSchema = z.record(z.string(), researchValueEntrySchema);
export type ResearchValueMap = z.infer<typeof researchValueMapSchema>;


// --- ASSET DESCRIPTIONS TABLE ---
// Stores reusable descriptions of the target asset class (e.g., "Luxury Boutique Hotel
// on 10+ acres"). These descriptions are fed to the AI research engine so it generates
// market data relevant to the exact type of property the fund is targeting.
export const assetDescriptions = pgTable("asset_descriptions", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  name: text("name").notNull(),
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
});

export const insertAssetDescriptionSchema = z.object({
  name: z.string(),
  isDefault: z.boolean().optional(),
});

export type AssetDescription = typeof assetDescriptions.$inferSelect;
export type InsertAssetDescription = z.infer<typeof insertAssetDescriptionSchema>;


// --- USER GROUPS TABLE ---
// Groups allow white-label branding per audience. Each group can have its own
// logo, color theme, and asset description. When a user belongs to a group,
// the UI renders that group's branding instead of the system default.
// Example: "Investor Portal" group sees a different logo than the internal team.
export const userGroups = pgTable("user_groups", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  name: text("name").notNull(),
  logoId: integer("logo_id").references(() => logos.id, { onDelete: "set null" }),
  themeId: integer("theme_id").references(() => designThemes.id, { onDelete: "set null" }),
  assetDescriptionId: integer("asset_description_id").references(() => assetDescriptions.id, { onDelete: "set null" }),
  isDefault: boolean("is_default").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
  index("user_groups_logo_id_idx").on(table.logoId),
  index("user_groups_theme_id_idx").on(table.themeId),
]);

export const insertUserGroupSchema = z.object({
  name: z.string().min(1),
  logoId: z.number().nullable().optional(),
  themeId: z.number().nullable().optional(),
  assetDescriptionId: z.number().nullable().optional(),
});

export type UserGroup = typeof userGroups.$inferSelect;
export type InsertUserGroup = z.infer<typeof insertUserGroupSchema>;



// --- DESIGN THEMES TABLE ---
// Color themes for the UI. Each theme has an ordered list of named colors
// (primary, secondary, accent, etc.) that the frontend applies as CSS variables.
// One theme is marked isDefault and used when no user/group preference exists.
// Admins can create, edit, and delete themes via the admin panel.
export const designThemes = pgTable("design_themes", {
  id: integer("id").primaryKey().generatedAlwaysAsIdentity(),
  name: text("name").notNull(),
  description: text("description").notNull(),
  colors: jsonb("colors").notNull().$type<DesignColor[]>(),
  iconSet: text("icon_set").notNull().default("lucide"),
  isDefault: boolean("is_default").notNull().default(false),
  isSystem: boolean("is_system").notNull().default(false),
  createdAt: timestamp("created_at").defaultNow().notNull(),
  updatedAt: timestamp("updated_at").defaultNow().notNull(),
});

export interface DesignColor {
  rank: number;
  name: string;
  hexCode: string;
  description: string;
}

export const insertDesignThemeSchema = z.object({
  name: z.string(),
  description: z.string(),
  colors: z.array(z.object({
    rank: z.number(),
    name: z.string(),
    hexCode: z.string(),
    description: z.string(),
  })),
  iconSet: z.enum(["lucide", "phosphor"]).optional(),
  isDefault: z.boolean().optional(),
});

export type DesignTheme = typeof designThemes.$inferSelect;
export type InsertDesignTheme = z.infer<typeof insertDesignThemeSchema>;

