import { db } from "../db";
import { properties, globalAssumptions, propertyFeeCategories, propertyPhotos } from "@shared/schema";
import { eq, isNull } from "drizzle-orm";
import { logger } from "../logger";
import {
  PropertyStatus,
  DEFAULT_REV_SHARE_EVENTS,
  DEFAULT_REV_SHARE_FB,
  DEFAULT_REV_SHARE_OTHER,
  DEFAULT_COST_RATE_ROOMS,
  DEFAULT_COST_RATE_FB,
  DEFAULT_COST_RATE_ADMIN,
  DEFAULT_COST_RATE_MARKETING,
  DEFAULT_COST_RATE_PROPERTY_OPS,
  DEFAULT_COST_RATE_UTILITIES,
  DEFAULT_COST_RATE_TAXES,
  DEFAULT_COST_RATE_IT,
  DEFAULT_COST_RATE_FFE,
  DEFAULT_COST_RATE_OTHER,
  DEFAULT_EXIT_CAP_RATE,
  DEFAULT_PROPERTY_TAX_RATE,
  DEFAULT_COMMISSION_RATE,
  DEFAULT_EVENT_EXPENSE_RATE,
  DEFAULT_OTHER_EXPENSE_RATE,
  DEFAULT_UTILITIES_VARIABLE_SPLIT,
  DEFAULT_OCCUPANCY_RAMP_MONTHS,
  DEFAULT_SAFE_VALUATION_CAP,
  DEFAULT_SAFE_DISCOUNT_RATE,
  DEFAULT_FUNDING_INTEREST_RATE,
  DEFAULT_FUNDING_INTEREST_PAYMENT_FREQUENCY,
  DEFAULT_BASE_MANAGEMENT_FEE_RATE,
  DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  SEED_DEBT_ASSUMPTIONS,
  DEFAULT_PROPERTY_INFLATION_RATE,
  DEFAULT_COMPANY_TAX_RATE,
  DEFAULT_BUSINESS_INSURANCE_START,
  DEFAULT_COST_RATE_INSURANCE,
  DEFAULT_LAND_VALUE_PERCENT,
  DEFAULT_SERVICE_FEE_CATEGORIES,
} from "@shared/constants";

export const SEED_COMPANY_IDENTITY = {
  companyName: "The Norfolk AI Group",
  companyPhone: "+1 (757) 555-0142",
  companyEmail: "info@norfolk.ai",
  companyWebsite: "https://norfolk.ai",
  companyEin: "92-1847356",
  companyFoundingYear: 2024,
  companyStreetAddress: "150 West Main Street, Suite 400",
  companyCity: "Norfolk",
  companyStateProvince: "VA",
  companyCountry: "United States",
  companyZipPostalCode: "23510",
  marcelaPhoneGreeting: "Hello, this is Marcela from The Norfolk AI Group. How can I help you today?",
} as const;

export const SEED_PROPERTY_DEFAULTS = {
  costRateRooms: DEFAULT_COST_RATE_ROOMS, costRateFB: DEFAULT_COST_RATE_FB, costRateAdmin: DEFAULT_COST_RATE_ADMIN,
  costRateMarketing: DEFAULT_COST_RATE_MARKETING, costRatePropertyOps: DEFAULT_COST_RATE_PROPERTY_OPS,
  costRateUtilities: DEFAULT_COST_RATE_UTILITIES,
  costRateTaxes: DEFAULT_COST_RATE_TAXES, costRateIT: DEFAULT_COST_RATE_IT, costRateFFE: DEFAULT_COST_RATE_FFE,
  costRateOther: DEFAULT_COST_RATE_OTHER, costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
  revShareEvents: DEFAULT_REV_SHARE_EVENTS,
  revShareFB: DEFAULT_REV_SHARE_FB, revShareOther: DEFAULT_REV_SHARE_OTHER,
  exitCapRate: DEFAULT_EXIT_CAP_RATE, taxRate: DEFAULT_PROPERTY_TAX_RATE,
  dispositionCommission: DEFAULT_COMMISSION_RATE,
  baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
  incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
};

export const DEFAULT_FEE_CATEGORIES = DEFAULT_SERVICE_FEE_CATEGORIES.map(c => ({
  name: c.name,
  rate: c.rate,
  sortOrder: c.sortOrder,
}));

export async function seedGlobalAssumptions() {
  // Check for a shared (userId IS NULL) row first — that's the canonical singleton
  const [shared] = await db.select().from(globalAssumptions)
    .where(isNull(globalAssumptions.userId))
    .limit(1);
  if (shared) return;

  // Fix legacy: if a non-shared row exists (userId != NULL), convert it to shared
  const [legacy] = await db.select().from(globalAssumptions).limit(1);
  if (legacy && legacy.userId !== null) {
    await db.update(globalAssumptions)
      .set({ userId: null, updatedAt: new Date() })
      .where(eq(globalAssumptions.id, legacy.id));
    logger.info("Converted legacy global assumptions to shared (userId=NULL)", "seed");
    return;
  }
  if (legacy) return; // Row exists with userId=null already

  await db.insert(globalAssumptions).values({
    userId: null,
    modelStartDate: "2026-04-01",
    companyOpsStartDate: "2026-06-01",
    fiscalYearStartMonth: 1,
    inflationRate: DEFAULT_PROPERTY_INFLATION_RATE,
    fixedCostEscalationRate: DEFAULT_PROPERTY_INFLATION_RATE,
    baseManagementFee: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFee: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    safeTranche1Amount: 1000000,
    safeTranche1Date: "2026-06-01",
    safeTranche2Amount: 1000000,
    safeTranche2Date: "2027-04-01",
    safeValuationCap: DEFAULT_SAFE_VALUATION_CAP,
    safeDiscountRate: DEFAULT_SAFE_DISCOUNT_RATE,
    fundingInterestRate: DEFAULT_FUNDING_INTEREST_RATE,
    fundingInterestPaymentFrequency: DEFAULT_FUNDING_INTEREST_PAYMENT_FREQUENCY,
    partnerCompYear1: 540000,
    partnerCompYear2: 540000,
    partnerCompYear3: 540000,
    partnerCompYear4: 600000,
    partnerCompYear5: 600000,
    partnerCompYear6: 700000,
    partnerCompYear7: 700000,
    partnerCompYear8: 800000,
    partnerCompYear9: 800000,
    partnerCompYear10: 900000,
    partnerCountYear1: 3,
    partnerCountYear2: 3,
    partnerCountYear3: 3,
    partnerCountYear4: 3,
    partnerCountYear5: 3,
    partnerCountYear6: 3,
    partnerCountYear7: 3,
    partnerCountYear8: 3,
    partnerCountYear9: 3,
    partnerCountYear10: 3,
    staffSalary: 75000,
    officeLeaseStart: 36000,
    professionalServicesStart: 24000,
    techInfraStart: 18000,
    businessInsuranceStart: DEFAULT_BUSINESS_INSURANCE_START,
    travelCostPerClient: 12000,
    itLicensePerClient: 3000,
    marketingRate: 0.05,
    miscOpsRate: 0.03,
    commissionRate: DEFAULT_COMMISSION_RATE,
    standardAcqPackage: {
      monthsToOps: 6,
      purchasePrice: 3800000,
      preOpeningCosts: 200000,
      operatingReserve: 250000,
      buildingImprovements: 1200000,
    },
    debtAssumptions: SEED_DEBT_ASSUMPTIONS,
    companyTaxRate: DEFAULT_COMPANY_TAX_RATE,
    ...SEED_COMPANY_IDENTITY,
    exitCapRate: DEFAULT_EXIT_CAP_RATE,
    salesCommissionRate: DEFAULT_COMMISSION_RATE,
    eventExpenseRate: DEFAULT_EVENT_EXPENSE_RATE,
    otherExpenseRate: DEFAULT_OTHER_EXPENSE_RATE,
    utilitiesVariableSplit: DEFAULT_UTILITIES_VARIABLE_SPLIT,
    assetDefinition: {
      minRooms: 10,
      maxRooms: 80,
      hasFB: true,
      hasEvents: true,
      hasWellness: true,
      minAdr: 150,
      maxAdr: 600,
      level: "luxury",
      eventLocations: 2,
      maxEventCapacity: 150,
      acreage: 10,
      privacyLevel: "high",
      parkingSpaces: 50,
      description: "Luxury boutique hotels on private estates of 10+ acres, catering to 100+ person exotic, unique, and corporate events in exclusive, secluded settings with full-service F&B, wellness programming, and curated guest experiences.",
    },
    icpConfig: {
      guestSegments: [
        { name: "Corporate Retreats", weight: 0.30, avgGroupSize: 25, avgStayNights: 3, seasonality: "year-round" },
        { name: "Luxury Leisure", weight: 0.25, avgGroupSize: 2, avgStayNights: 4, seasonality: "peak" },
        { name: "Weddings & Social Events", weight: 0.20, avgGroupSize: 80, avgStayNights: 2, seasonality: "spring-fall" },
        { name: "Wellness Retreats", weight: 0.15, avgGroupSize: 12, avgStayNights: 5, seasonality: "year-round" },
        { name: "Adventure & Experiential", weight: 0.10, avgGroupSize: 6, avgStayNights: 3, seasonality: "seasonal" },
      ],
      demographics: {
        ageRange: "35-65",
        incomeLevel: "HHI $250K+",
        geography: "US East Coast, Latin America, International",
        travelStyle: "Experiential luxury, privacy-focused",
      },
      bookingBehavior: {
        leadTimeDays: 90,
        directBookingPct: 0.60,
        repeatGuestPct: 0.35,
        avgRevenuePerGuest: 1200,
      },
    },
    researchConfig: {
      property: {
        enabled: true,
        focusAreas: ["boutique hospitality", "luxury lodging", "event venues", "F&B operations", "wellness tourism"],
        regions: ["US Northeast", "US Mountain West", "Colombia", "Latin America"],
        timeHorizon: "10-year",
        customInstructions: "Focus on boutique hotels with 10-80 rooms, event-driven revenue models, and properties on 10+ acre estates. Emphasize AI-driven operations and technology integration.",
        customQuestions: "",
        enabledTools: [],
      },
      company: {
        enabled: true,
        focusAreas: ["hospitality management companies", "hotel investment", "PropTech", "AI in hospitality"],
        regions: ["United States", "Latin America"],
        timeHorizon: "5-year",
        customInstructions: "Research AI-powered hospitality management trends, boutique hotel acquisition strategies, and technology-driven operational efficiencies.",
        customQuestions: "",
        enabledTools: [],
      },
    },
  });
  logger.info("Seeded global assumptions (The Norfolk AI Group)", "seed");
}

export async function seedProperties() {
  await db.insert(properties).values([
    {
      userId: null,
      name: "Jano Grande Ranch",
      description: "A luxury hacienda retreat set in the lush hills of Antioquia, offering curated cultural experiences and farm-to-table dining amid Colombia's coffee country.",
      streetAddress: "Vereda El Salado",
      city: "Medellín",
      stateProvince: "Antioquia",
      zipPostalCode: "050001",
      country: "Colombia",
      location: "Antioquia, Medellín",
      market: "Latin America",
      imageUrl: "/images/property-medellin.png",
      status: PropertyStatus.PLANNED,
      acquisitionDate: "2026-06-01",
      operationsStartDate: "2026-12-01",
      purchasePrice: 1200000,
      buildingImprovements: 400000,
      preOpeningCosts: 150000,
      operatingReserve: 300000,
      roomCount: 20,
      startAdr: 250,
      adrGrowthRate: 0.035,
      startOccupancy: 0.40,
      maxOccupancy: 0.72,
      occupancyRampMonths: 9,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
      type: "Full Equity",
      willRefinance: "Yes",
      refinanceDate: "2029-12-01",
      refinanceLTV: 0.75,
      refinanceInterestRate: 0.09,
      refinanceTermYears: 25,
      refinanceClosingCostRate: 0.03,
      refinanceYearsAfterAcquisition: 3,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: 0.17,
      costRateFB: 0.10,
      costRateAdmin: 0.06,
      costRateMarketing: 0.015,
      costRatePropertyOps: 0.05,
      costRateUtilities: 0.04,
      
      costRateTaxes: 0.016,
      costRateIT: 0.005,
      costRateFFE: 0.04,
      costRateOther: 0.05,
      revShareEvents: 0.30,
      revShareFB: 0.25,
      revShareOther: 0.08,
      cateringBoostPercent: 0.25,
      exitCapRate: 0.10,
      taxRate: 0.09,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      userId: null,
      name: "Loch Sheldrake",
      description: "A serene lakeside retreat in Sullivan County's Catskill region, blending rustic charm with modern luxury for year-round mountain and lake experiences.",
      streetAddress: "Loch Sheldrake",
      city: "Loch Sheldrake",
      stateProvince: "New York",
      zipPostalCode: "12759",
      country: "United States",
      location: "Sullivan County, New York",
      market: "North America",
      imageUrl: "/images/property-loch-sheldrake.png",
      status: PropertyStatus.PLANNED,
      acquisitionDate: "2026-11-01",
      operationsStartDate: "2027-05-01",
      purchasePrice: 3000000,
      buildingImprovements: 1000000,
      preOpeningCosts: 150000,
      operatingReserve: 400000,
      roomCount: 20,
      startAdr: 280,
      adrGrowthRate: 0.035,
      startOccupancy: 0.50,
      maxOccupancy: 0.68,
      occupancyRampMonths: 4,
      stabilizationMonths: 18,
      occupancyGrowthStep: 0.05,
      type: "Full Equity",
      willRefinance: "Yes",
      refinanceDate: "2030-05-01",
      refinanceLTV: 0.75,
      refinanceInterestRate: 0.09,
      refinanceTermYears: 25,
      refinanceClosingCostRate: 0.03,
      refinanceYearsAfterAcquisition: 3,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: 0.19,
      costRateFB: 0.09,
      costRateAdmin: 0.07,
      costRateMarketing: 0.02,
      costRatePropertyOps: 0.055,
      costRateUtilities: 0.055,
      
      costRateTaxes: 0.035,
      costRateIT: 0.005,
      costRateFFE: 0.04,
      costRateOther: 0.04,
      revShareEvents: 0.35,
      revShareFB: 0.25,
      revShareOther: 0.08,
      cateringBoostPercent: 0.22,
      exitCapRate: 0.09,
      taxRate: 0.25,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      userId: null,
      name: "Belleayre Mountain",
      description: "An alpine lodge nestled in the Western Catskills, offering four-season mountain recreation with ski-in access and panoramic ridge-line views.",
      streetAddress: "Upper Delaware River Valley",
      city: "Highmount",
      stateProvince: "New York",
      zipPostalCode: "12441",
      country: "United States",
      location: "Western Catskills, New York",
      market: "North America",
      imageUrl: "/images/property-belleayre.png",
      status: PropertyStatus.PLANNED,
      acquisitionDate: "2027-03-01",
      operationsStartDate: "2027-09-01",
      purchasePrice: 3500000,
      buildingImprovements: 800000,
      preOpeningCosts: 250000,
      operatingReserve: 500000,
      roomCount: 20,
      startAdr: 320,
      adrGrowthRate: 0.035,
      startOccupancy: 0.40,
      maxOccupancy: 0.68,
      occupancyRampMonths: 12,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
      type: "Full Equity",
      willRefinance: "Yes",
      refinanceDate: "2030-09-01",
      refinanceLTV: 0.75,
      refinanceInterestRate: 0.09,
      refinanceTermYears: 25,
      refinanceClosingCostRate: 0.03,
      refinanceYearsAfterAcquisition: 3,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: 0.20,
      costRateFB: 0.09,
      costRateAdmin: 0.08,
      costRateMarketing: 0.02,
      costRatePropertyOps: 0.06,
      costRateUtilities: 0.055,
      
      costRateTaxes: 0.035,
      costRateIT: 0.005,
      costRateFFE: 0.04,
      costRateOther: 0.04,
      revShareEvents: 0.30,
      revShareFB: 0.28,
      revShareOther: 0.07,
      cateringBoostPercent: 0.20,
      exitCapRate: 0.085,
      taxRate: 0.25,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      userId: null,
      name: "Scott's House",
      description: "A modern mountain retreat in Utah's Ogden Valley, combining contemporary design with dramatic Wasatch Range views and year-round outdoor adventure.",
      streetAddress: "Eden",
      city: "Eden",
      stateProvince: "Utah",
      zipPostalCode: "84310",
      country: "United States",
      location: "Ogden Valley, Utah",
      market: "North America",
      imageUrl: "/images/property-eden.png",
      status: PropertyStatus.PLANNED,
      acquisitionDate: "2027-08-01",
      operationsStartDate: "2028-02-01",
      purchasePrice: 3200000,
      buildingImprovements: 800000,
      preOpeningCosts: 200000,
      operatingReserve: 400000,
      roomCount: 20,
      startAdr: 350,
      adrGrowthRate: 0.03,
      startOccupancy: 0.45,
      maxOccupancy: 0.65,
      occupancyRampMonths: 6,
      stabilizationMonths: 24,
      occupancyGrowthStep: 0.05,
      type: "Financed",
      acquisitionLTV: 0.60,
      acquisitionInterestRate: 0.07,
      acquisitionTermYears: 25,
      acquisitionClosingCostRate: 0.025,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: 0.20,
      costRateFB: 0.08,
      costRateAdmin: 0.07,
      costRateMarketing: 0.02,
      costRatePropertyOps: 0.05,
      costRateUtilities: 0.05,
      
      costRateTaxes: 0.02,
      costRateIT: 0.005,
      costRateFFE: 0.04,
      costRateOther: 0.04,
      revShareEvents: 0.30,
      revShareFB: 0.20,
      revShareOther: 0.08,
      cateringBoostPercent: 0.20,
      exitCapRate: 0.085,
      taxRate: 0.22,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      userId: null,
      name: "Lakeview Haven Lodge",
      description: "A lakefront lodge overlooking Pineview Reservoir in Ogden Valley, offering tranquil waterfront living with mountain-backed sunsets and kayaking.",
      streetAddress: "Pineview Reservoir",
      city: "Huntsville",
      stateProvince: "Utah",
      zipPostalCode: "84317",
      country: "United States",
      location: "Ogden Valley, Utah",
      market: "North America",
      imageUrl: "/images/property-huntsville.png",
      status: PropertyStatus.PLANNED,
      acquisitionDate: "2027-12-01",
      operationsStartDate: "2028-06-01",
      purchasePrice: 3800000,
      buildingImprovements: 1200000,
      preOpeningCosts: 250000,
      operatingReserve: 500000,
      roomCount: 20,
      startAdr: 320,
      adrGrowthRate: 0.03,
      startOccupancy: 0.50,
      maxOccupancy: 0.68,
      occupancyRampMonths: 3,
      stabilizationMonths: 18,
      occupancyGrowthStep: 0.05,
      type: "Financed",
      acquisitionLTV: 0.65,
      acquisitionInterestRate: 0.07,
      acquisitionTermYears: 25,
      acquisitionClosingCostRate: 0.025,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: 0.20,
      costRateFB: 0.09,
      costRateAdmin: 0.07,
      costRateMarketing: 0.02,
      costRatePropertyOps: 0.055,
      costRateUtilities: 0.05,
      
      costRateTaxes: 0.02,
      costRateIT: 0.005,
      costRateFFE: 0.04,
      costRateOther: 0.04,
      revShareEvents: 0.28,
      revShareFB: 0.22,
      revShareOther: 0.10,
      cateringBoostPercent: 0.18,
      exitCapRate: 0.08,
      taxRate: 0.22,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      userId: null,
      name: "San Diego",
      description: "A colonial boutique hotel in Cartagena's historic walled city, blending 17th-century architecture with Caribbean luxury, rooftop dining, and old-world charm.",
      streetAddress: "Cochera del Hobo, Barrio San Diego",
      city: "Cartagena",
      stateProvince: "Bolívar",
      zipPostalCode: "130001",
      country: "Colombia",
      location: "Cartagena, Colombia",
      market: "Latin America",
      imageUrl: "/images/property-cartagena.png",
      status: PropertyStatus.PLANNED,
      acquisitionDate: "2028-04-01",
      operationsStartDate: "2028-10-01",
      purchasePrice: 2000000,
      buildingImprovements: 1000000,
      preOpeningCosts: 250000,
      operatingReserve: 500000,
      roomCount: 20,
      startAdr: 240,
      adrGrowthRate: 0.035,
      startOccupancy: 0.42,
      maxOccupancy: 0.72,
      occupancyRampMonths: 10,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
      type: "Financed",
      acquisitionLTV: 0.60,
      acquisitionInterestRate: 0.095,
      acquisitionTermYears: 25,
      acquisitionClosingCostRate: 0.02,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: 0.17,
      costRateFB: 0.09,
      costRateAdmin: 0.07,
      costRateMarketing: 0.015,
      costRatePropertyOps: 0.035,
      costRateUtilities: 0.04,
      
      costRateTaxes: 0.025,
      costRateIT: 0.005,
      costRateFFE: 0.04,
      costRateOther: 0.04,
      revShareEvents: 0.30,
      revShareFB: 0.24,
      revShareOther: 0.06,
      cateringBoostPercent: 0.20,
      exitCapRate: 0.09,
      taxRate: 0.35,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
  ]);
  
  const seededProperties = await db.select().from(properties);
  logger.info(`Seeded ${seededProperties.length} properties (Norfolk AI portfolio)`, "seed");
}

export const SEED_SYNC_PROPERTIES = [
  { ...SEED_PROPERTY_DEFAULTS, name: "The Hudson Estate", streetAddress: "142 Old Post Road", city: "Millbrook", stateProvince: "NY", zipPostalCode: "12545", country: "United States", location: "Hudson Valley, New York", market: "North America", imageUrl: "/images/property-ny.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2026-06-01", operationsStartDate: "2026-12-01", purchasePrice: 3800000, buildingImprovements: 1200000, preOpeningCosts: 200000, operatingReserve: 250000, roomCount: 20, startAdr: 385, adrGrowthRate: 0.025, startOccupancy: 0.55, maxOccupancy: 0.82, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Full Equity", costRateFB: 0.085, costRateIT: 0.005, cateringBoostPercent: 0.22, exitCapRate: 0.08, willRefinance: "Yes", refinanceDate: "2029-12-01", refinanceLtv: 0.75, refinanceInterestRate: 0.09, refinanceTermYears: 25, refinanceClosingCostRate: 0.03, revShareEvents: 0.30 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Eden Summit Lodge", streetAddress: "3850 Nordic Valley Road", city: "Eden", stateProvince: "UT", zipPostalCode: "84310", location: "Ogden Valley, Utah", market: "North America", imageUrl: "/images/property-utah.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2027-01-01", operationsStartDate: "2027-07-01", purchasePrice: 4000000, buildingImprovements: 1200000, preOpeningCosts: 200000, operatingReserve: 250000, roomCount: 20, startAdr: 425, adrGrowthRate: 0.025, startOccupancy: 0.50, maxOccupancy: 0.80, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Full Equity", costRateFB: 0.085, costRateIT: 0.005, cateringBoostPercent: 0.25, willRefinance: "Yes", refinanceDate: "2030-07-01", refinanceLtv: 0.75, refinanceInterestRate: 0.09, refinanceTermYears: 25, refinanceClosingCostRate: 0.03, revShareEvents: 0.30 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Austin Hillside", streetAddress: "4100 Mount Bonnell Drive", city: "Austin", stateProvince: "TX", zipPostalCode: "78731", location: "Hill Country, Texas", market: "North America", imageUrl: "/images/property-austin.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2027-04-01", operationsStartDate: "2028-01-01", purchasePrice: 3500000, buildingImprovements: 1100000, preOpeningCosts: 200000, operatingReserve: 250000, roomCount: 20, startAdr: 320, adrGrowthRate: 0.025, startOccupancy: 0.55, maxOccupancy: 0.82, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Full Equity", costRateFB: 0.09, costRateIT: 0.005, cateringBoostPercent: 0.20, willRefinance: "Yes", refinanceDate: "2031-01-01", refinanceLtv: 0.75, refinanceInterestRate: 0.09, refinanceTermYears: 25, refinanceClosingCostRate: 0.03, revShareEvents: 0.28 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Casa Medellín", streetAddress: "Carrera 43A #7-50, El Poblado", city: "Medellín", stateProvince: "Antioquia", zipPostalCode: "050021", location: "El Poblado, Medellín", market: "Latin America", imageUrl: "/images/property-medellin.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2026-09-01", operationsStartDate: "2028-07-01", purchasePrice: 3800000, buildingImprovements: 1000000, preOpeningCosts: 200000, operatingReserve: 600000, roomCount: 30, startAdr: 210, adrGrowthRate: 0.04, startOccupancy: 0.50, maxOccupancy: 0.78, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Financed", costRateFB: 0.075, costRateIT: 0.005, cateringBoostPercent: 0.18, exitCapRate: 0.095, acquisitionLTV: 0.60, acquisitionInterestRate: 0.095, acquisitionTermYears: 25, acquisitionClosingCostRate: 0.02, revShareEvents: 0.25 },
  { ...SEED_PROPERTY_DEFAULTS, name: "Blue Ridge Manor", streetAddress: "275 Elk Mountain Scenic Highway", city: "Asheville", stateProvince: "NC", zipPostalCode: "28804", location: "Blue Ridge Mountains, North Carolina", market: "North America", imageUrl: "/images/property-asheville.png", status: PropertyStatus.PIPELINE, acquisitionDate: "2027-07-01", operationsStartDate: "2028-07-01", purchasePrice: 6000000, buildingImprovements: 1500000, preOpeningCosts: 250000, operatingReserve: 500000, roomCount: 30, startAdr: 375, adrGrowthRate: 0.025, startOccupancy: 0.50, maxOccupancy: 0.80, occupancyRampMonths: 6, occupancyGrowthStep: 0.05, type: "Financed", costRateFB: 0.10, costRateIT: 0.005, cateringBoostPercent: 0.25, exitCapRate: 0.09, acquisitionLTV: 0.60, acquisitionInterestRate: 0.09, acquisitionTermYears: 25, acquisitionClosingCostRate: 0.02, revShareEvents: 0.28 },
];

export async function seedMedellinDuplex() {
  const existing = await db.select({ id: properties.id, name: properties.name })
    .from(properties)
    .where(eq(properties.name, "Medellin Duplex"))
    .limit(1);

  if (existing.length > 0) return;

  await db.insert(properties).values({
    userId: null,
    name: "Medellin Duplex",
    description: "A stunning two-story luxury duplex apartment in El Poblado, Medellín's most exclusive residential zone. Contemporary open-concept design with double-height ceilings, floating staircase, Calacatta marble kitchen island, and panoramic city and Andes mountain views from floor-to-ceiling windows across 350 square meters on two floors.",
    streetAddress: "Calle 10 #43A-22, El Poblado",
    city: "Medellín",
    stateProvince: "Antioquia",
    zipPostalCode: "050021",
    country: "Colombia",
    location: "El Poblado, Medellín, Colombia",
    market: "Latin America",
    imageUrl: "/images/medellin-duplex-1.jpeg",
    status: PropertyStatus.ACQUIRED,
    acquisitionDate: "2025-03-01",
    operationsStartDate: "2025-09-01",
    purchasePrice: 800000,
    buildingImprovements: 150000,
    landValuePercent: DEFAULT_LAND_VALUE_PERCENT,
    preOpeningCosts: 15000,
    operatingReserve: 60000,
    roomCount: 4,
    startAdr: 350,
    adrGrowthRate: 0.04,
    startOccupancy: 0.62,
    maxOccupancy: 0.82,
    occupancyRampMonths: 4,
    stabilizationMonths: 12,
    occupancyGrowthStep: 0.04,
    type: "Full Equity",
    willRefinance: "No",
    costRateRooms: 0.14,
    costRateFB: 0.06,
    costRateAdmin: 0.07,
    costRateMarketing: 0.02,
    costRatePropertyOps: 0.04,
    costRateUtilities: 0.04,
    costRateTaxes: 0.018,
    costRateIT: 0.005,
    costRateFFE: 0.03,
    costRateOther: 0.04,
    costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
    revShareEvents: 0.10,
    revShareFB: 0.12,
    revShareOther: 0.06,
    cateringBoostPercent: 0.10,
    exitCapRate: 0.08,
    taxRate: 0.35,
    countryRiskPremium: 0.0275,
    dispositionCommission: DEFAULT_COMMISSION_RATE,
    baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    latitude: 6.2086,
    longitude: -75.5659,
    isActive: true,
  });

  logger.info("Seeded Medellin Duplex property", "seed");
}

export async function seedMedellinDuplexPhotos() {
  const [prop] = await db.select({ id: properties.id })
    .from(properties)
    .where(eq(properties.name, "Medellin Duplex"))
    .limit(1);

  if (!prop) return;

  const existing = await db.select({ id: propertyPhotos.id })
    .from(propertyPhotos)
    .where(eq(propertyPhotos.propertyId, prop.id))
    .limit(1);

  if (existing.length > 0) return;

  const photos = [
    { imageUrl: "/images/medellin-duplex-1.jpeg", caption: "Open-concept living and dining area with Calacatta marble island and floating staircase", sortOrder: 0, isHero: true },
    { imageUrl: "/images/medellin-duplex-2.jpeg", caption: "Chef's kitchen with marble waterfall island and panoramic Andes mountain views", sortOrder: 1, isHero: false },
    { imageUrl: "/images/medellin-duplex-3.jpeg", caption: "Master suite with floor-to-ceiling windows overlooking Medellín's skyline and mountains", sortOrder: 2, isHero: false },
  ];

  for (const photo of photos) {
    await db.insert(propertyPhotos).values({
      propertyId: prop.id,
      imageUrl: photo.imageUrl,
      caption: photo.caption,
      sortOrder: photo.sortOrder,
      isHero: photo.isHero,
    });
  }

  logger.info("Seeded 3 photos for Medellin Duplex", "seed");
}

export async function seedFeeCategories() {
  const allProps = await db.select({ id: properties.id }).from(properties);

  let inserted = 0;
  for (const prop of allProps) {
    const existingCats = await db.select({ name: propertyFeeCategories.name })
      .from(propertyFeeCategories)
      .where(eq(propertyFeeCategories.propertyId, prop.id));
    const existingNames = new Set(existingCats.map(c => c.name));

    for (const cat of DEFAULT_FEE_CATEGORIES) {
      if (!existingNames.has(cat.name)) {
        await db.insert(propertyFeeCategories).values({
          propertyId: prop.id,
          name: cat.name,
          rate: cat.rate,
          isActive: true,
          sortOrder: cat.sortOrder,
        });
        inserted++;
      }
    }
  }
  if (inserted > 0) {
    logger.info(`Seeded ${inserted} fee categories across ${allProps.length} properties`, "seed");
  }
}
