import { db } from "../db";
import { properties, globalAssumptions, propertyFeeCategories } from "@shared/schema";
import { logger } from "../logger";
import {
  DEFAULT_REV_SHARE_EVENTS,
  DEFAULT_REV_SHARE_FB,
  DEFAULT_REV_SHARE_OTHER,
  DEFAULT_COST_RATE_ROOMS,
  DEFAULT_COST_RATE_FB,
  DEFAULT_COST_RATE_ADMIN,
  DEFAULT_COST_RATE_MARKETING,
  DEFAULT_COST_RATE_PROPERTY_OPS,
  DEFAULT_COST_RATE_UTILITIES,
  DEFAULT_COST_RATE_INSURANCE,
  DEFAULT_COST_RATE_TAXES,
  DEFAULT_COST_RATE_IT,
  DEFAULT_COST_RATE_FFE,
  DEFAULT_COST_RATE_OTHER,
  DEFAULT_EXIT_CAP_RATE,
  DEFAULT_TAX_RATE,
  DEFAULT_COMMISSION_RATE,
  DEFAULT_EVENT_EXPENSE_RATE,
  DEFAULT_OTHER_EXPENSE_RATE,
  DEFAULT_UTILITIES_VARIABLE_SPLIT,
  DEFAULT_OCCUPANCY_RAMP_MONTHS,
  DEFAULT_SAFE_VALUATION_CAP,
  DEFAULT_SAFE_DISCOUNT_RATE,
  DEFAULT_BASE_MANAGEMENT_FEE_RATE,
  DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  SEED_DEBT_ASSUMPTIONS,
} from "@shared/constants";

export async function seedGlobalAssumptions() {
  await db.insert(globalAssumptions).values({
    modelStartDate: "2026-04-01",
    companyOpsStartDate: "2026-06-01",
    fiscalYearStartMonth: 1,
    inflationRate: 0.03,
    fixedCostEscalationRate: 0.03,
    baseManagementFee: 0.085,
    incentiveManagementFee: 0.12,
    safeTranche1Amount: 1000000,
    safeTranche1Date: "2026-06-01",
    safeTranche2Amount: 1000000,
    safeTranche2Date: "2027-04-01",
    safeValuationCap: DEFAULT_SAFE_VALUATION_CAP,
    safeDiscountRate: DEFAULT_SAFE_DISCOUNT_RATE,
    partnerCompYear1: 540000,
    partnerCompYear2: 540000,
    partnerCompYear3: 540000,
    partnerCompYear4: 600000,
    partnerCompYear5: 600000,
    partnerCompYear6: 700000,
    partnerCompYear7: 700000,
    partnerCompYear8: 800000,
    partnerCompYear9: 800000,
    partnerCompYear10: 900000,
    partnerCountYear1: 3,
    partnerCountYear2: 3,
    partnerCountYear3: 3,
    partnerCountYear4: 3,
    partnerCountYear5: 3,
    partnerCountYear6: 3,
    partnerCountYear7: 3,
    partnerCountYear8: 3,
    partnerCountYear9: 3,
    partnerCountYear10: 3,
    staffSalary: 75000,
    officeLeaseStart: 36000,
    professionalServicesStart: 24000,
    techInfraStart: 18000,
    businessInsuranceStart: 12000,
    travelCostPerClient: 12000,
    itLicensePerClient: 3000,
    marketingRate: 0.05,
    miscOpsRate: 0.03,
    commissionRate: DEFAULT_COMMISSION_RATE,
    standardAcqPackage: {
      monthsToOps: 6,
      purchasePrice: 3800000,
      preOpeningCosts: 200000,
      operatingReserve: 250000,
      buildingImprovements: 1200000,
    },
    debtAssumptions: SEED_DEBT_ASSUMPTIONS,
    companyTaxRate: 0.3,
    companyName: "Hospitality Business Group",
    exitCapRate: DEFAULT_EXIT_CAP_RATE,
    salesCommissionRate: DEFAULT_COMMISSION_RATE,
    eventExpenseRate: DEFAULT_EVENT_EXPENSE_RATE,
    otherExpenseRate: DEFAULT_OTHER_EXPENSE_RATE,
    utilitiesVariableSplit: DEFAULT_UTILITIES_VARIABLE_SPLIT,
  });
  logger.info("Seeded global assumptions", "seed");
}

export async function seedProperties() {
  await db.insert(properties).values([
    {
      name: "The Hudson Estate",
      streetAddress: "142 Old Post Road",
      city: "Millbrook",
      stateProvince: "NY",
      zipPostalCode: "12545",
      location: "Hudson Valley, New York",
      market: "North America",
      imageUrl: "/images/property-ny.png",
      status: "Pipeline",
      acquisitionDate: "2026-06-01",
      operationsStartDate: "2026-12-01",
      purchasePrice: 3800000,
      buildingImprovements: 1200000,
      preOpeningCosts: 200000,
      operatingReserve: 250000,
      roomCount: 20,
      startAdr: 385,
      adrGrowthRate: 0.025,
      startOccupancy: 0.55,
      maxOccupancy: 0.82,
      occupancyRampMonths: DEFAULT_OCCUPANCY_RAMP_MONTHS,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
     
      type: "Full Equity",

      willRefinance: "Yes",
      refinanceDate: "2029-12-01",
      refinanceLTV: SEED_DEBT_ASSUMPTIONS.refiLTV,
      refinanceInterestRate: SEED_DEBT_ASSUMPTIONS.interestRate,
      refinanceTermYears: SEED_DEBT_ASSUMPTIONS.amortizationYears,
      refinanceClosingCostRate: SEED_DEBT_ASSUMPTIONS.refiClosingCostRate,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: DEFAULT_COST_RATE_ROOMS,
      costRateFB: 0.085,
      costRateAdmin: DEFAULT_COST_RATE_ADMIN,
      costRateMarketing: DEFAULT_COST_RATE_MARKETING,
      costRatePropertyOps: DEFAULT_COST_RATE_PROPERTY_OPS,
      costRateUtilities: DEFAULT_COST_RATE_UTILITIES,
      costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
      costRateTaxes: DEFAULT_COST_RATE_TAXES,
      costRateIT: DEFAULT_COST_RATE_IT,
      costRateFFE: DEFAULT_COST_RATE_FFE,
      costRateOther: DEFAULT_COST_RATE_OTHER,
      revShareEvents: DEFAULT_REV_SHARE_EVENTS,
      revShareFB: DEFAULT_REV_SHARE_FB,
      revShareOther: DEFAULT_REV_SHARE_OTHER,
      cateringBoostPercent: 0.22,
      exitCapRate: 0.08,
      taxRate: DEFAULT_TAX_RATE,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      name: "Eden Summit Lodge",
      streetAddress: "3850 Nordic Valley Road",
      city: "Eden",
      stateProvince: "UT",
      zipPostalCode: "84310",
      location: "Ogden Valley, Utah",
      market: "North America",
      imageUrl: "/images/property-utah.png",
      status: "Pipeline",
      acquisitionDate: "2027-01-01",
      operationsStartDate: "2027-07-01",
      purchasePrice: 4000000,
      buildingImprovements: 1200000,
      preOpeningCosts: 200000,
      operatingReserve: 250000,
      roomCount: 20,
      startAdr: 425,
      adrGrowthRate: 0.025,
      startOccupancy: 0.50,
      maxOccupancy: 0.80,
      occupancyRampMonths: DEFAULT_OCCUPANCY_RAMP_MONTHS,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
     
      type: "Full Equity",

      willRefinance: "Yes",
      refinanceDate: "2030-07-01",
      refinanceLTV: SEED_DEBT_ASSUMPTIONS.refiLTV,
      refinanceInterestRate: SEED_DEBT_ASSUMPTIONS.interestRate,
      refinanceTermYears: SEED_DEBT_ASSUMPTIONS.amortizationYears,
      refinanceClosingCostRate: SEED_DEBT_ASSUMPTIONS.refiClosingCostRate,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: DEFAULT_COST_RATE_ROOMS,
      costRateFB: 0.085,
      costRateAdmin: DEFAULT_COST_RATE_ADMIN,
      costRateMarketing: DEFAULT_COST_RATE_MARKETING,
      costRatePropertyOps: DEFAULT_COST_RATE_PROPERTY_OPS,
      costRateUtilities: DEFAULT_COST_RATE_UTILITIES,
      costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
      costRateTaxes: DEFAULT_COST_RATE_TAXES,
      costRateIT: DEFAULT_COST_RATE_IT,
      costRateFFE: DEFAULT_COST_RATE_FFE,
      costRateOther: DEFAULT_COST_RATE_OTHER,
      revShareEvents: DEFAULT_REV_SHARE_EVENTS,
      revShareFB: DEFAULT_REV_SHARE_FB,
      revShareOther: DEFAULT_REV_SHARE_OTHER,
      cateringBoostPercent: 0.25,
      exitCapRate: DEFAULT_EXIT_CAP_RATE,
      taxRate: DEFAULT_TAX_RATE,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      name: "Austin Hillside",
      streetAddress: "4100 Mount Bonnell Drive",
      city: "Austin",
      stateProvince: "TX",
      zipPostalCode: "78731",
      location: "Hill Country, Texas",
      market: "North America",
      imageUrl: "/images/property-austin.png",
      status: "Pipeline",
      acquisitionDate: "2027-04-01",
      operationsStartDate: "2028-01-01",
      purchasePrice: 3500000,
      buildingImprovements: 1100000,
      preOpeningCosts: 200000,
      operatingReserve: 250000,
      roomCount: 20,
      startAdr: 320,
      adrGrowthRate: 0.025,
      startOccupancy: 0.55,
      maxOccupancy: 0.82,
      occupancyRampMonths: DEFAULT_OCCUPANCY_RAMP_MONTHS,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
     
      type: "Full Equity",

      willRefinance: "Yes",
      refinanceDate: "2031-01-01",
      refinanceLTV: SEED_DEBT_ASSUMPTIONS.refiLTV,
      refinanceInterestRate: SEED_DEBT_ASSUMPTIONS.interestRate,
      refinanceTermYears: SEED_DEBT_ASSUMPTIONS.amortizationYears,
      refinanceClosingCostRate: SEED_DEBT_ASSUMPTIONS.refiClosingCostRate,
      dispositionCommission: DEFAULT_COMMISSION_RATE,
      costRateRooms: DEFAULT_COST_RATE_ROOMS,
      costRateFB: 0.09,
      costRateAdmin: DEFAULT_COST_RATE_ADMIN,
      costRateMarketing: DEFAULT_COST_RATE_MARKETING,
      costRatePropertyOps: DEFAULT_COST_RATE_PROPERTY_OPS,
      costRateUtilities: DEFAULT_COST_RATE_UTILITIES,
      costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
      costRateTaxes: DEFAULT_COST_RATE_TAXES,
      costRateIT: DEFAULT_COST_RATE_IT,
      costRateFFE: DEFAULT_COST_RATE_FFE,
      costRateOther: DEFAULT_COST_RATE_OTHER,
      revShareEvents: 0.28,
      revShareFB: DEFAULT_REV_SHARE_FB,
      revShareOther: DEFAULT_REV_SHARE_OTHER,
      cateringBoostPercent: 0.20,
      exitCapRate: DEFAULT_EXIT_CAP_RATE,
      taxRate: DEFAULT_TAX_RATE,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      name: "Casa Medellín",
      streetAddress: "Carrera 43A #7-50, El Poblado",
      city: "Medellín",
      stateProvince: "Antioquia",
      zipPostalCode: "050021",
      location: "El Poblado, Medellín",
      market: "Latin America",
      imageUrl: "/images/property-medellin.png",
      status: "Pipeline",
      acquisitionDate: "2026-09-01",
      operationsStartDate: "2028-07-01",
      purchasePrice: 3800000,
      buildingImprovements: 1000000,
      preOpeningCosts: 200000,
      operatingReserve: 600000,
      roomCount: 30,
      startAdr: 210,
      adrGrowthRate: 0.04,
      startOccupancy: 0.50,
      maxOccupancy: 0.78,
      occupancyRampMonths: DEFAULT_OCCUPANCY_RAMP_MONTHS,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
     
      type: "Financed",
      acquisitionLTV: 0.60,
      acquisitionInterestRate: 0.095,
      acquisitionTermYears: 25,
      acquisitionClosingCostRate: 0.02,
      dispositionCommission: DEFAULT_COMMISSION_RATE,

      costRateRooms: DEFAULT_COST_RATE_ROOMS,
      costRateFB: 0.075,
      costRateAdmin: DEFAULT_COST_RATE_ADMIN,
      costRateMarketing: DEFAULT_COST_RATE_MARKETING,
      costRatePropertyOps: DEFAULT_COST_RATE_PROPERTY_OPS,
      costRateUtilities: DEFAULT_COST_RATE_UTILITIES,
      costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
      costRateTaxes: DEFAULT_COST_RATE_TAXES,
      costRateIT: DEFAULT_COST_RATE_IT,
      costRateFFE: DEFAULT_COST_RATE_FFE,
      costRateOther: DEFAULT_COST_RATE_OTHER,
      revShareEvents: 0.25,
      revShareFB: DEFAULT_REV_SHARE_FB,
      revShareOther: DEFAULT_REV_SHARE_OTHER,
      cateringBoostPercent: 0.18,
      exitCapRate: 0.095,
      taxRate: DEFAULT_TAX_RATE,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
    {
      name: "Blue Ridge Manor",
      streetAddress: "275 Elk Mountain Scenic Highway",
      city: "Asheville",
      stateProvince: "NC",
      zipPostalCode: "28804",
      location: "Blue Ridge Mountains, North Carolina",
      market: "North America",
      imageUrl: "/images/property-asheville.png",
      status: "Pipeline",
      acquisitionDate: "2027-07-01",
      operationsStartDate: "2028-07-01",
      purchasePrice: 6000000,
      buildingImprovements: 1500000,
      preOpeningCosts: 250000,
      operatingReserve: 500000,
      roomCount: 30,
      startAdr: 375,
      adrGrowthRate: 0.025,
      startOccupancy: 0.50,
      maxOccupancy: 0.80,
      occupancyRampMonths: DEFAULT_OCCUPANCY_RAMP_MONTHS,
      stabilizationMonths: 36,
      occupancyGrowthStep: 0.05,
     
      type: "Financed",
      acquisitionLTV: 0.60,
      acquisitionInterestRate: 0.09,
      acquisitionTermYears: 25,
      acquisitionClosingCostRate: 0.02,
      dispositionCommission: DEFAULT_COMMISSION_RATE,

      costRateRooms: DEFAULT_COST_RATE_ROOMS,
      costRateFB: 0.10,
      costRateAdmin: DEFAULT_COST_RATE_ADMIN,
      costRateMarketing: DEFAULT_COST_RATE_MARKETING,
      costRatePropertyOps: DEFAULT_COST_RATE_PROPERTY_OPS,
      costRateUtilities: DEFAULT_COST_RATE_UTILITIES,
      costRateInsurance: DEFAULT_COST_RATE_INSURANCE,
      costRateTaxes: DEFAULT_COST_RATE_TAXES,
      costRateIT: DEFAULT_COST_RATE_IT,
      costRateFFE: DEFAULT_COST_RATE_FFE,
      costRateOther: DEFAULT_COST_RATE_OTHER,
      revShareEvents: 0.28,
      revShareFB: DEFAULT_REV_SHARE_FB,
      revShareOther: DEFAULT_REV_SHARE_OTHER,
      cateringBoostPercent: 0.25,
      exitCapRate: 0.09,
      taxRate: DEFAULT_TAX_RATE,
      baseManagementFeeRate: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
      incentiveManagementFeeRate: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    },
  ]);
  
  const seededProperties = await db.select().from(properties);
  logger.info(`Seeded ${seededProperties.length} properties`, "seed");
}

export async function seedFeeCategories() {
  const existing = await db.select().from(propertyFeeCategories).limit(1);
  if (existing.length > 0) return;

  const allProps = await db.select({ id: properties.id }).from(properties);
  const defaultCategories = [
    { name: "Marketing", rate: 0.02, sortOrder: 1 },
    { name: "IT", rate: 0.01, sortOrder: 2 },
    { name: "Accounting", rate: 0.015, sortOrder: 3 },
    { name: "Reservations", rate: 0.02, sortOrder: 4 },
    { name: "General Management", rate: 0.02, sortOrder: 5 },
  ];

  for (const prop of allProps) {
    for (const cat of defaultCategories) {
      await db.insert(propertyFeeCategories).values({
        propertyId: prop.id,
        name: cat.name,
        rate: cat.rate,
        isActive: true,
        sortOrder: cat.sortOrder,
      });
    }
  }
  logger.info(`Seeded fee categories for ${allProps.length} properties`, "seed");
}

