import {
  DEFAULT_EXIT_CAP_RATE,
  DEFAULT_PROPERTY_TAX_RATE,
  DEFAULT_COMMISSION_RATE,
  DEFAULT_BASE_MANAGEMENT_FEE_RATE,
  DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
  DEFAULT_COST_RATE_ROOMS,
  DEFAULT_COST_RATE_FB,
  DEFAULT_COST_RATE_ADMIN,
  DEFAULT_COST_RATE_MARKETING,
  DEFAULT_COST_RATE_PROPERTY_OPS,
  DEFAULT_COST_RATE_UTILITIES,
  DEFAULT_COST_RATE_TAXES,
  DEFAULT_COST_RATE_IT,
  DEFAULT_COST_RATE_FFE,
  DEFAULT_COST_RATE_OTHER,
  DEFAULT_COST_RATE_INSURANCE,
  DEFAULT_REV_SHARE_EVENTS,
  DEFAULT_REV_SHARE_FB,
  DEFAULT_REV_SHARE_OTHER,
  DEFAULT_START_ADR,
  DEFAULT_ADR_GROWTH_RATE,
  DEFAULT_START_OCCUPANCY,
  DEFAULT_MAX_OCCUPANCY,
  DEFAULT_OCCUPANCY_RAMP_MONTHS,
  DEFAULT_ROOM_COUNT,
  DEFAULT_CATERING_BOOST_PCT,
  DEFAULT_LAND_VALUE_PERCENT,
  DEFAULT_LTV,
  DEFAULT_INTEREST_RATE,
  DEFAULT_TERM_YEARS,
  SEED_DEBT_ASSUMPTIONS,
} from "./constants";

export type FieldType = "rate" | "currency" | "integer" | "decimal";
export type FieldScope = "property";
export type FieldCategory =
  | "exit"
  | "revenue"
  | "cost-rate"
  | "management-fee"
  | "operating"
  | "debt-acquisition"
  | "debt-refinance";

export type GaSource =
  | { kind: "direct"; gaField: string }
  | { kind: "debt"; debtField: string };

export interface FieldDefinition {
  propertyField: string;
  label: string;
  type: FieldType;
  scope: FieldScope;
  category: FieldCategory;
  fallback: number;
  gaSource: GaSource;
  engineImpact: boolean;
  validationMin?: number;
  validationMax?: number;
}

export const FIELD_REGISTRY: readonly FieldDefinition[] = [
  {
    propertyField: "exitCapRate",
    label: "Exit Cap Rate",
    type: "rate",
    scope: "property",
    category: "exit",
    fallback: DEFAULT_EXIT_CAP_RATE,
    gaSource: { kind: "direct", gaField: "exitCapRate" },
    engineImpact: true,
    validationMin: 0.01,
    validationMax: 1,
  },
  {
    propertyField: "taxRate",
    label: "Income Tax Rate",
    type: "rate",
    scope: "property",
    category: "exit",
    fallback: DEFAULT_PROPERTY_TAX_RATE,
    gaSource: { kind: "direct", gaField: "defaultPropertyTaxRate" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "dispositionCommission",
    label: "Disposition Commission",
    type: "rate",
    scope: "property",
    category: "exit",
    fallback: DEFAULT_COMMISSION_RATE,
    gaSource: { kind: "direct", gaField: "salesCommissionRate" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "baseManagementFeeRate",
    label: "Base Management Fee Rate",
    type: "rate",
    scope: "property",
    category: "management-fee",
    fallback: DEFAULT_BASE_MANAGEMENT_FEE_RATE,
    gaSource: { kind: "direct", gaField: "baseManagementFee" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "incentiveManagementFeeRate",
    label: "Incentive Management Fee Rate",
    type: "rate",
    scope: "property",
    category: "management-fee",
    fallback: DEFAULT_INCENTIVE_MANAGEMENT_FEE_RATE,
    gaSource: { kind: "direct", gaField: "incentiveManagementFee" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "startAdr",
    label: "Starting ADR",
    type: "currency",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_START_ADR,
    gaSource: { kind: "direct", gaField: "defaultStartAdr" },
    engineImpact: true,
    validationMin: 1,
  },
  {
    propertyField: "adrGrowthRate",
    label: "ADR Growth Rate",
    type: "rate",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_ADR_GROWTH_RATE,
    gaSource: { kind: "direct", gaField: "defaultAdrGrowthRate" },
    engineImpact: true,
  },
  {
    propertyField: "startOccupancy",
    label: "Starting Occupancy",
    type: "rate",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_START_OCCUPANCY,
    gaSource: { kind: "direct", gaField: "defaultStartOccupancy" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "maxOccupancy",
    label: "Max Occupancy",
    type: "rate",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_MAX_OCCUPANCY,
    gaSource: { kind: "direct", gaField: "defaultMaxOccupancy" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "occupancyRampMonths",
    label: "Occupancy Ramp Months",
    type: "integer",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_OCCUPANCY_RAMP_MONTHS,
    gaSource: { kind: "direct", gaField: "defaultOccupancyRampMonths" },
    engineImpact: true,
    validationMin: 0,
  },
  {
    propertyField: "roomCount",
    label: "Room Count",
    type: "integer",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_ROOM_COUNT,
    gaSource: { kind: "direct", gaField: "defaultRoomCount" },
    engineImpact: true,
    validationMin: 1,
  },
  {
    propertyField: "cateringBoostPercent",
    label: "Catering Boost %",
    type: "rate",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_CATERING_BOOST_PCT,
    gaSource: { kind: "direct", gaField: "defaultCateringBoostPct" },
    engineImpact: true,
    validationMin: 0,
  },
  {
    propertyField: "costRateRooms",
    label: "Cost Rate — Rooms",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_ROOMS,
    gaSource: { kind: "direct", gaField: "defaultCostRateRooms" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateFB",
    label: "Cost Rate — F&B",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_FB,
    gaSource: { kind: "direct", gaField: "defaultCostRateFb" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateAdmin",
    label: "Cost Rate — Admin",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_ADMIN,
    gaSource: { kind: "direct", gaField: "defaultCostRateAdmin" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateMarketing",
    label: "Cost Rate — Marketing",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_MARKETING,
    gaSource: { kind: "direct", gaField: "defaultCostRateMarketing" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRatePropertyOps",
    label: "Cost Rate — Property Ops",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_PROPERTY_OPS,
    gaSource: { kind: "direct", gaField: "defaultCostRatePropertyOps" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateUtilities",
    label: "Cost Rate — Utilities",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_UTILITIES,
    gaSource: { kind: "direct", gaField: "defaultCostRateUtilities" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateTaxes",
    label: "Cost Rate — Taxes",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_TAXES,
    gaSource: { kind: "direct", gaField: "defaultCostRateTaxes" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateIT",
    label: "Cost Rate — IT",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_IT,
    gaSource: { kind: "direct", gaField: "defaultCostRateIt" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateFFE",
    label: "Cost Rate — FF&E",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_FFE,
    gaSource: { kind: "direct", gaField: "defaultCostRateFfe" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateOther",
    label: "Cost Rate — Other",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_OTHER,
    gaSource: { kind: "direct", gaField: "defaultCostRateOther" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "costRateInsurance",
    label: "Cost Rate — Insurance",
    type: "rate",
    scope: "property",
    category: "cost-rate",
    fallback: DEFAULT_COST_RATE_INSURANCE,
    gaSource: { kind: "direct", gaField: "defaultCostRateInsurance" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "revShareEvents",
    label: "Revenue Share — Events",
    type: "rate",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_REV_SHARE_EVENTS,
    gaSource: { kind: "direct", gaField: "defaultRevShareEvents" },
    engineImpact: true,
    validationMin: 0,
  },
  {
    propertyField: "revShareFB",
    label: "Revenue Share — F&B",
    type: "rate",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_REV_SHARE_FB,
    gaSource: { kind: "direct", gaField: "defaultRevShareFb" },
    engineImpact: true,
    validationMin: 0,
  },
  {
    propertyField: "revShareOther",
    label: "Revenue Share — Other",
    type: "rate",
    scope: "property",
    category: "revenue",
    fallback: DEFAULT_REV_SHARE_OTHER,
    gaSource: { kind: "direct", gaField: "defaultRevShareOther" },
    engineImpact: true,
    validationMin: 0,
  },
  {
    propertyField: "landValuePercent",
    label: "Land Value %",
    type: "rate",
    scope: "property",
    category: "operating",
    fallback: DEFAULT_LAND_VALUE_PERCENT,
    gaSource: { kind: "direct", gaField: "defaultLandValuePercent" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "acquisitionLTV",
    label: "Acquisition LTV",
    type: "rate",
    scope: "property",
    category: "debt-acquisition",
    fallback: DEFAULT_LTV,
    gaSource: { kind: "debt", debtField: "acqLTV" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "acquisitionInterestRate",
    label: "Acquisition Interest Rate",
    type: "rate",
    scope: "property",
    category: "debt-acquisition",
    fallback: DEFAULT_INTEREST_RATE,
    gaSource: { kind: "debt", debtField: "interestRate" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "acquisitionTermYears",
    label: "Acquisition Term (Years)",
    type: "integer",
    scope: "property",
    category: "debt-acquisition",
    fallback: DEFAULT_TERM_YEARS,
    gaSource: { kind: "debt", debtField: "amortizationYears" },
    engineImpact: true,
    validationMin: 1,
  },
  {
    propertyField: "acquisitionClosingCostRate",
    label: "Acquisition Closing Cost Rate",
    type: "rate",
    scope: "property",
    category: "debt-acquisition",
    fallback: SEED_DEBT_ASSUMPTIONS.acqClosingCostRate,
    gaSource: { kind: "debt", debtField: "acqClosingCostRate" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "refinanceLTV",
    label: "Refinance LTV",
    type: "rate",
    scope: "property",
    category: "debt-refinance",
    fallback: DEFAULT_LTV,
    gaSource: { kind: "debt", debtField: "refiLTV" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "refinanceInterestRate",
    label: "Refinance Interest Rate",
    type: "rate",
    scope: "property",
    category: "debt-refinance",
    fallback: DEFAULT_INTEREST_RATE,
    gaSource: { kind: "debt", debtField: "interestRate" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
  {
    propertyField: "refinanceTermYears",
    label: "Refinance Term (Years)",
    type: "integer",
    scope: "property",
    category: "debt-refinance",
    fallback: DEFAULT_TERM_YEARS,
    gaSource: { kind: "debt", debtField: "amortizationYears" },
    engineImpact: true,
    validationMin: 1,
  },
  {
    propertyField: "refinanceClosingCostRate",
    label: "Refinance Closing Cost Rate",
    type: "rate",
    scope: "property",
    category: "debt-refinance",
    fallback: SEED_DEBT_ASSUMPTIONS.refiClosingCostRate,
    gaSource: { kind: "debt", debtField: "refiClosingCostRate" },
    engineImpact: true,
    validationMin: 0,
    validationMax: 1,
  },
] as const;

export interface DebtAssumptions {
  acqLTV?: number;
  refiLTV?: number;
  interestRate?: number;
  amortizationYears?: number;
  acqClosingCostRate?: number;
  refiClosingCostRate?: number;
}

export function buildPropertyDefaultsFromRegistry(
  ga?: Record<string, unknown> | null,
): Record<string, unknown> {
  const debt = ((ga?.debtAssumptions as DebtAssumptions) ?? {}) as Record<string, number | undefined>;
  const result: Record<string, unknown> = {};

  for (const field of FIELD_REGISTRY) {
    let gaValue: unknown;
    if (field.gaSource.kind === "direct") {
      gaValue = ga?.[field.gaSource.gaField];
    } else {
      gaValue = debt[field.gaSource.debtField];
    }
    result[field.propertyField] = gaValue ?? field.fallback;
  }

  return result;
}
