import type { ThemePreset } from "./types";

export const PRESET_THEMES: ThemePreset[] = [
  {
    name: "Studio Noir",
    description:
      "Crisp black and white with precise gray layers. Minimal, authoritative, and razor-sharp. Green accent cuts through the monochrome with surgical clarity.",
    isDefault: false,
    colors: [
      { rank: 1, name: "Carbon",          hexCode: "#18181B", description: "PALETTE: Primary brand color. Near-black for buttons, active nav, focus rings." },
      { rank: 2, name: "Graphite",        hexCode: "#3F3F46", description: "PALETTE: Secondary accent. Dark gray for contrast badges and secondary elements." },
      { rank: 3, name: "White",           hexCode: "#FFFFFF", description: "PALETTE: Background and card surfaces. Pure white canvas." },
      { rank: 4, name: "Ink",             hexCode: "#09090B", description: "PALETTE: Foreground text. True black for maximum readability." },
      { rank: 5, name: "Smoke",           hexCode: "#F4F4F5", description: "PALETTE: Muted surfaces. Light gray for secondary cards and table alternates." },
      { rank: 6, name: "Silver",          hexCode: "#E4E4E7", description: "PALETTE: Borders and input outlines. Clean gray border." },
      { rank: 1, name: "Emerald",         hexCode: "#10B981", description: "ACCENT: Standout highlight for IRR circles, key KPIs, and success badges." },
      { rank: 2, name: "Amber",           hexCode: "#F59E0B", description: "ACCENT: Secondary emphasis for charts, infographics, and comparative metrics." },
      { rank: 1, name: "Emerald",         hexCode: "#10B981", description: "CHART: Primary series — revenue and key metrics." },
      { rank: 2, name: "Amber",           hexCode: "#F59E0B", description: "CHART: Secondary series — net income and profitability." },
      { rank: 3, name: "Rose",            hexCode: "#F43F5E", description: "CHART: Tertiary series — cash flow and operational metrics." },
      { rank: 4, name: "Sky",             hexCode: "#0EA5E9", description: "CHART: Quaternary series — expenses and budget." },
      { rank: 5, name: "Violet",          hexCode: "#8B5CF6", description: "CHART: Quinary series — background and comparison." },
      { rank: 1, name: "Emerald",         hexCode: "#10B981", description: "LINE: Primary line — revenue trend." },
      { rank: 2, name: "Amber",           hexCode: "#F59E0B", description: "LINE: Secondary line — income trend." },
      { rank: 3, name: "Rose",            hexCode: "#F43F5E", description: "LINE: Tertiary line — expense trend." },
      { rank: 4, name: "Sky",             hexCode: "#0EA5E9", description: "LINE: Quaternary line — cash flow trend." },
      { rank: 5, name: "Violet",          hexCode: "#8B5CF6", description: "LINE: Quinary line — projection overlay." },
    ],
  },
  {
    name: "Tuscan Olive Grove",
    description:
      "Sun-dappled olive and warm earth tones. Inspired by Mediterranean hillsides, blending natural elegance with grounded sophistication.",
    isDefault: false,
    colors: [
      { rank: 1, name: "Olive Sage",      hexCode: "#5C7049", description: "PALETTE: Primary brand color. Deep olive-green for buttons, active nav, focus rings. WCAG AA compliant on light backgrounds." },
      { rank: 2, name: "Deep Moss",       hexCode: "#4A5D3F", description: "PALETTE: Secondary accent. Deep forest moss for contrast badges and secondary elements." },
      { rank: 3, name: "Warm Sand",       hexCode: "#FAF6F1", description: "PALETTE: Background and card surfaces. Warm sandy cream for an inviting canvas." },
      { rank: 4, name: "Bark Brown",      hexCode: "#3B3832", description: "PALETTE: Foreground text. Deep brown-charcoal for readable, warm type." },
      { rank: 5, name: "Stone",           hexCode: "#EDEBE7", description: "PALETTE: Muted surfaces. Warm stone for secondary cards and table alternates." },
      { rank: 6, name: "Clay Border",     hexCode: "#D8D3CC", description: "PALETTE: Borders and input outlines. Subtle warm clay tone." },
      { rank: 1, name: "Tuscan Gold",     hexCode: "#C4A35A", description: "ACCENT: Standout highlight for IRR circles, key KPIs, and achievement badges." },
      { rank: 2, name: "Deep Forest",     hexCode: "#2D6A4F", description: "ACCENT: Secondary emphasis for charts, infographics, and comparative metrics." },
      { rank: 1, name: "Forest",          hexCode: "#2D6A4F", description: "CHART: Primary series — revenue and key metrics." },
      { rank: 2, name: "Terracotta",      hexCode: "#C17853", description: "CHART: Secondary series — net income and profitability." },
      { rank: 3, name: "Plum",            hexCode: "#7E3F8E", description: "CHART: Tertiary series — warm contrast for cash flow data." },
      { rank: 4, name: "Gold",            hexCode: "#B8860B", description: "CHART: Quaternary series — expenses and budget metrics." },
      { rank: 5, name: "Clay",            hexCode: "#A0522D", description: "CHART: Quinary series — alerts and negative variance." },
      { rank: 1, name: "Forest",          hexCode: "#2D6A4F", description: "LINE: Primary line — revenue trend." },
      { rank: 2, name: "Terracotta",      hexCode: "#C17853", description: "LINE: Secondary line — income trend." },
      { rank: 3, name: "Plum",            hexCode: "#7E3F8E", description: "LINE: Tertiary line — expense trend." },
      { rank: 4, name: "Gold",            hexCode: "#B8860B", description: "LINE: Quaternary line — cash flow trend." },
      { rank: 5, name: "Clay",            hexCode: "#A0522D", description: "LINE: Quinary line — projection overlay." },
    ],
  },
  {
    name: "Starlit Harbor",
    description:
      "Deep navy twilight over calm waters. A commanding palette that conveys trust, authority, and the quiet confidence of a harbor at dusk.",
    isDefault: false,
    colors: [
      { rank: 1, name: "Navy",            hexCode: "#2C3E6B", description: "PALETTE: Primary brand color. Deep navy for buttons, active elements, and focus rings." },
      { rank: 2, name: "Royal Blue",      hexCode: "#1A2B5E", description: "PALETTE: Secondary accent. Darker indigo for badges and contrast elements." },
      { rank: 3, name: "Cool White",      hexCode: "#F8F9FC", description: "PALETTE: Background and card surfaces. Crisp cool-toned white." },
      { rank: 4, name: "Ink",             hexCode: "#1E293B", description: "PALETTE: Foreground text. Deep slate-ink for sharp, professional type." },
      { rank: 5, name: "Ice Gray",        hexCode: "#EFF1F5", description: "PALETTE: Muted surfaces. Cool ice gray for secondary cards and rows." },
      { rank: 6, name: "Steel Border",    hexCode: "#D1D5E0", description: "PALETTE: Borders and input outlines. Subtle cool-toned steel." },
      { rank: 1, name: "Harbor Gold",     hexCode: "#F59E0B", description: "ACCENT: Standout highlight for IRR circles, key KPIs, and achievement badges." },
      { rank: 2, name: "Azure",           hexCode: "#2563EB", description: "ACCENT: Secondary emphasis for charts, infographics, and comparative metrics." },
      { rank: 1, name: "Navy",            hexCode: "#2C3E6B", description: "CHART: Primary series — revenue and key metrics." },
      { rank: 2, name: "Cobalt",          hexCode: "#3B82F6", description: "CHART: Secondary series — growth and income metrics." },
      { rank: 3, name: "Violet",          hexCode: "#7C3AED", description: "CHART: Tertiary series — cash flow and EBITDA." },
      { rank: 4, name: "Teal",            hexCode: "#0D9488", description: "CHART: Quaternary series — operations and costs." },
      { rank: 5, name: "Coral",           hexCode: "#F43F5E", description: "CHART: Quinary series — alerts and shortfalls." },
      { rank: 1, name: "Azure",           hexCode: "#2563EB", description: "LINE: Primary line — revenue trend." },
      { rank: 2, name: "Amber",           hexCode: "#D97706", description: "LINE: Secondary line — income trend." },
      { rank: 3, name: "Emerald",         hexCode: "#059669", description: "LINE: Tertiary line — expense trend." },
      { rank: 4, name: "Rose",            hexCode: "#E11D48", description: "LINE: Quaternary line — cash flow trend." },
      { rank: 5, name: "Violet",          hexCode: "#7C3AED", description: "LINE: Quinary line — projection overlay." },
    ],
  },
  {
    name: "Coastal Breeze",
    description:
      "Rich teal and sea glass tones. Inspired by ocean horizons and coastal luxury — fresh, vibrant, and unmistakably modern.",
    isDefault: false,
    colors: [
      { rank: 1, name: "Teal",            hexCode: "#0D7377", description: "PALETTE: Primary brand color. Rich teal for buttons, active states, focus rings." },
      { rank: 2, name: "Deep Ocean",      hexCode: "#065F5F", description: "PALETTE: Secondary accent. Deep ocean green for contrast and emphasis." },
      { rank: 3, name: "Seafoam White",   hexCode: "#F7FBFA", description: "PALETTE: Background and card surfaces. Clean white with a cool aqua hint." },
      { rank: 4, name: "Dark Slate",      hexCode: "#1A2F2F", description: "PALETTE: Foreground text. Dark teal-slate for cohesive type." },
      { rank: 5, name: "Mist",            hexCode: "#EEF4F3", description: "PALETTE: Muted surfaces. Cool mist for secondary cards and rows." },
      { rank: 6, name: "Sea Glass",       hexCode: "#CADBD8", description: "PALETTE: Borders and input outlines. Subtle sea glass tone." },
      { rank: 1, name: "Coral Sunset",    hexCode: "#F97316", description: "ACCENT: Standout highlight for IRR circles, key KPIs, and achievement badges." },
      { rank: 2, name: "Teal",            hexCode: "#0D7377", description: "ACCENT: Secondary emphasis for charts, infographics, and comparative metrics." },
      { rank: 1, name: "Teal",            hexCode: "#0D7377", description: "CHART: Primary series — revenue and key metrics." },
      { rank: 2, name: "Deep Ocean",      hexCode: "#065F5F", description: "CHART: Secondary series — profitability and margins." },
      { rank: 3, name: "Coral",           hexCode: "#F97316", description: "CHART: Tertiary series — warm contrast for cash flow." },
      { rank: 4, name: "Cyan",            hexCode: "#06B6D4", description: "CHART: Quaternary series — operations and costs." },
      { rank: 5, name: "Rose",            hexCode: "#E11D48", description: "CHART: Quinary series — alerts and shortfalls." },
      { rank: 1, name: "Teal",            hexCode: "#0F766E", description: "LINE: Primary line — revenue trend." },
      { rank: 2, name: "Orange",          hexCode: "#EA580C", description: "LINE: Secondary line — income trend." },
      { rank: 3, name: "Indigo",          hexCode: "#4F46E5", description: "LINE: Tertiary line — expense trend." },
      { rank: 4, name: "Pink",            hexCode: "#DB2777", description: "LINE: Quaternary line — cash flow trend." },
      { rank: 5, name: "Lime",            hexCode: "#65A30D", description: "LINE: Quinary line — projection overlay." },
    ],
  },
  {
    name: "Electric Twilight",
    description:
      "Warm violet and deep indigo under a lavender sky. Creative energy meets professional clarity — bold, imaginative, and forward-thinking.",
    isDefault: false,
    colors: [
      { rank: 1, name: "Violet",          hexCode: "#6344E0", description: "PALETTE: Primary brand color. Deep violet-purple for buttons, active nav, focus rings. WCAG AA compliant on light backgrounds." },
      { rank: 2, name: "Deep Indigo",     hexCode: "#5B3FD6", description: "PALETTE: Secondary accent. Deep indigo for contrast badges and emphasis." },
      { rank: 3, name: "Lavender White",  hexCode: "#FAF9FE", description: "PALETTE: Background and card surfaces. Soft lavender-tinted white." },
      { rank: 4, name: "Dark Plum",       hexCode: "#1E1B2E", description: "PALETTE: Foreground text. Deep plum-charcoal for sharp, readable type." },
      { rank: 5, name: "Mist Lilac",      hexCode: "#F0EEF6", description: "PALETTE: Muted surfaces. Soft lilac-gray for secondary cards and table alternates." },
      { rank: 6, name: "Heather",         hexCode: "#D5D1E1", description: "PALETTE: Borders and input outlines. Subtle heather-purple border tone." },
      { rank: 1, name: "Electric Amber",  hexCode: "#F59E0B", description: "ACCENT: Standout highlight for IRR circles, key KPIs, and achievement badges." },
      { rank: 2, name: "Cyan",            hexCode: "#06B6D4", description: "ACCENT: Secondary emphasis for charts, infographics, and comparative metrics." },
      { rank: 1, name: "Violet",          hexCode: "#7C5CFC", description: "CHART: Primary series — revenue and key metrics." },
      { rank: 2, name: "Indigo",          hexCode: "#5B3FD6", description: "CHART: Secondary series — net income and profitability." },
      { rank: 3, name: "Amber",           hexCode: "#F59E0B", description: "CHART: Tertiary series — warm contrast for cash flow data." },
      { rank: 4, name: "Teal",            hexCode: "#14B8A6", description: "CHART: Quaternary series — operations and cost metrics." },
      { rank: 5, name: "Rose",            hexCode: "#F43F5E", description: "CHART: Quinary series — alerts and negative variance." },
      { rank: 1, name: "Purple",          hexCode: "#7C3AED", description: "LINE: Primary line — revenue trend." },
      { rank: 2, name: "Cyan",            hexCode: "#06B6D4", description: "LINE: Secondary line — income trend." },
      { rank: 3, name: "Amber",           hexCode: "#D97706", description: "LINE: Tertiary line — expense trend." },
      { rank: 4, name: "Rose",            hexCode: "#F43F5E", description: "LINE: Quaternary line — cash flow trend." },
      { rank: 5, name: "Emerald",         hexCode: "#10B981", description: "LINE: Quinary line — projection overlay." },
    ],
  },
  {
    name: "Claude",
    description:
      "Warm terracotta and cream inspired by Anthropic's Claude interface. Earthy, approachable, and quietly confident — professional warmth without pretension.",
    isDefault: false,
    colors: [
      { rank: 1, name: "Terracotta",       hexCode: "#B85C3A", description: "PALETTE: Primary brand color. Rich terracotta for buttons, active nav, focus rings. WCAG AA compliant on light backgrounds." },
      { rank: 2, name: "Warm Umber",       hexCode: "#8B6F5E", description: "PALETTE: Secondary accent. Muted warm brown for contrast badges and secondary elements." },
      { rank: 3, name: "Cream",            hexCode: "#FAF7F4", description: "PALETTE: Background and card surfaces. Warm off-white cream canvas." },
      { rank: 4, name: "Charcoal",         hexCode: "#2D2B28", description: "PALETTE: Foreground text. Near-black warm charcoal for readable type." },
      { rank: 5, name: "Linen",            hexCode: "#F0EBE5", description: "PALETTE: Muted surfaces. Light warm beige for secondary cards and table alternates." },
      { rank: 6, name: "Sand Border",      hexCode: "#E5DED6", description: "PALETTE: Borders and input outlines. Subtle warm gray border tone." },
      { rank: 1, name: "Teal",             hexCode: "#0D9488", description: "ACCENT: Standout highlight for IRR circles, key KPIs, and success badges." },
      { rank: 2, name: "Warm Amber",       hexCode: "#D4A76A", description: "ACCENT: Secondary emphasis for charts, infographics, and comparative metrics." },
      { rank: 1, name: "Teal",             hexCode: "#0D9488", description: "CHART: Primary series — revenue and key metrics." },
      { rank: 2, name: "Terracotta",       hexCode: "#D97757", description: "CHART: Secondary series — net income and profitability." },
      { rank: 3, name: "Slate Blue",       hexCode: "#6B7FA3", description: "CHART: Tertiary series — cash flow and operational metrics." },
      { rank: 4, name: "Amber",            hexCode: "#D4A76A", description: "CHART: Quaternary series — expenses and budget." },
      { rank: 5, name: "Muted Plum",       hexCode: "#9B7A94", description: "CHART: Quinary series — background and comparison." },
      { rank: 1, name: "Teal",             hexCode: "#0D9488", description: "LINE: Primary line — revenue trend." },
      { rank: 2, name: "Terracotta",       hexCode: "#D97757", description: "LINE: Secondary line — income trend." },
      { rank: 3, name: "Slate Blue",       hexCode: "#6B7FA3", description: "LINE: Tertiary line — expense trend." },
      { rank: 4, name: "Amber",            hexCode: "#D4A76A", description: "LINE: Quaternary line — cash flow trend." },
      { rank: 5, name: "Muted Plum",       hexCode: "#9B7A94", description: "LINE: Quinary line — projection overlay." },
    ],
  },
];

export function getPresetByName(name: string): ThemePreset | undefined {
  return PRESET_THEMES.find(t => t.name === name);
}

export function getPresetNames(): string[] {
  return PRESET_THEMES.map(t => t.name);
}
